### ISSUE TITLE
crash after server join, pls fix it

### ISSUE THREAD

**Issue by m4d-m4x** [WildBamaBoy/minecraft-comes-alive#1002]
Crash only on multiplayer, if i play on singleplayer, I dont have any problems. Pls fix it.
[crash-2018-03-20_21.52.48-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1831270/crash-2018-03-20_21.52.48-client.txt)

**Comment by Akaruz64** [comment]
Im having the same issue after some playing, get a random crash cause by Ticking Entity

-- Head --
Thread: Client thread
Stacktrace:
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: mca:villagermca (mca.entity.EntityVillagerMCA)
	Entity ID: 36678
	Entity Name: Steve
	Entity's Exact location: 289.50, 45.00, -669.50
	Entity's Block location: World: (289,45,-670), Chunk: (at 1,2,2 in 18,-42; contains blocks 288,0,-672 to 303,255,-657), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)


MC Ver is 1.12.2
Forge  Ver 14.23.2.2654  
MCA Ver 1.12.2-5.3.1
