### ISSUE TITLE
[1.12.2 v5.3.1][core radixcore 2.2.1]Crash when getting close to city

### ISSUE THREAD

**Issue by winsrp** [WildBamaBoy/minecraft-comes-alive#1014]
Getting close to a city crashed the client (not the server) with the following

`[12:00:35] [main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215) ~[VillagerAttributes.class:?]
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678) ~[EntityVillagerMCA.class:?]
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800) ~[EntityVillagerMCA.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1611) ~[vp.class:?]
	at DynamicLights.getLightLevel(DynamicLights.java:334) ~[DynamicLights.class:?]
	at DynamicLights.updateMapDynamicLights(DynamicLights.java:117) ~[DynamicLights.class:?]
	at DynamicLights.update(DynamicLights.java:91) ~[DynamicLights.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1182) ~[buy.class:?]
	at shadersmod.client.ShadersRender.setupTerrain(ShadersRender.java:58) ~[ShadersRender.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1723) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[12:00:36] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----`

**Comment by MokahTGS** [comment]
Getting the same in a SP and LAN player environment.  The SP host player doesn't crash, but the LAN player does.

Here's the crash log from their CPU: https://pastebin.com/j9SMGn1A

**Comment by lymem** [comment]
I'm getting the same issue on a private server I host, the player will crash the first time a village is encountered and the server needs to be rebooted to fix.. crash log:


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
at net.minecraft.world.World.func_72866_a(World.java:1990)
at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
Entity Type: mca:villagermca (mca.entity.EntityVillagerMCA)
Entity ID: 10376486
Entity Name: Steve
Entity's Exact location: 614.50, 64.00, 1307.50
Entity's Block location: World: (614,64,1307), Chunk: (at 6,4,11 in 38,81; contains blocks 608,0,1296 to 623,255,1311), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
Entity's Momentum: 0.00, -0.08, 0.00
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['PangPingpong'/10375607, l='MpServer', x=566.96, y=77.74, z=1302.29]]
Chunk stats: MultiplayerChunkCache: 387, 387
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (136,64,256), Chunk: (at 8,4,0 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 41713929 game time, 14360160 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 34 total; [EntityPlayerSP['PangPingpong'/10375607,

**Comment by C0rn3j** [comment]
Still an issue with forge 2760 and whatever is the current mod version
