### ISSUE TITLE
mca:memorial returned a null ItemStack in getPickBlock

### ISSUE THREAD

**Issue by cowpod** [WildBamaBoy/minecraft-comes-alive#1028]
This occurred when a wife/husband/etc has died and you look at the ring on the ground, or the "mca:memorial". This error is reported by HWaila.
Please fix this! Simply logging in again crashes the game immediately.
Minecraft version: 1.12.2
Mod version:  5.3.1

Crash log section below, whole crash log is at the bottom.
`[16:44:39] [main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: mca:memorial from mod Minecraft Comes Alive returned a null ItemStack in getPickBlock(...). Please report this to them.
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:64) ~[DataAccessorCommon.class:?]
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44) ~[DataAccessorCommon.class:?]
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76) ~[WailaTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_209_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
`
[crash-2018-05-22_16.33.13-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2029311/crash-2018-05-22_16.33.13-client.txt)

**Comment by Mariomm-marti** [comment]
Almost 3 months from the open of this issue, any answer @cowpod ?

**Comment by Mariomm-marti** [comment]
I didn't read the stacktrace. It seems it's a Hywla/Waila issue as they are not checking the property they are asking for to be null.

I mark my issue as solved as is Hwyla/Waila issue.

**Comment by cowpod** [comment]
This is on purpose on Hwyla's part - apparently (for them) it is 'bad style'? Closing.
