### ISSUE TITLE
java.lang.Float cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by cowpod** [WildBamaBoy/minecraft-comes-alive#1029]
This crash occurred shortly after killing a werewolf, and now crashes the whole game every time i attempt to log in to the world.
Minecraft Version: 1.12.2
Mod version: 5.3.1
Whole crash log is also attached at the bottom.
`java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`
[crash-2018-05-22_17.10.01-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2029347/crash-2018-05-22_17.10.01-client.txt)

**Comment by adkins2010** [comment]
I wanted to contribute to the main fork of this project.  I tried reaching out to WildBamaBoy, but I haven't heard back from him yet.  
This wouldn't correspond to my code yet, and I wouldn't be able to figure out where your problem occurred without being able to know what happened when this occurred.  
If you want to try out my branch where I incorporate a more medieval approach to this mod then please let me know and I can provide you with a runnable JAR for your Minecraft game.  Or, you can git-clone and build yourself.

**Comment by SpringsTS** [comment]
@adkins2010 
I'm interested in your fork, I would like to try it, if you can provide a .jar file. Thank you in advance.

**Comment by viveleroi** [comment]
I had this problem too, on the first-time render of my first village in a new world.

```
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
	at mca.actions.AbstractToggleAction.getIsActive(AbstractToggleAction.java:41)
	at mca.entity.VillagerBehaviors.isToggleActionActive(VillagerBehaviors.java:139)
	at mca.client.render.RenderVillagerMCA.doRenderEffects(RenderVillagerMCA.java:172)
	at mca.client.render.RenderVillagerMCA.doRender(RenderVillagerMCA.java:367)
	at mca.client.render.RenderVillagerMCA.func_76986_a(RenderVillagerMCA.java:34)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

[Full crash report](https://pste.me/#/O3Vqn)
