### ISSUE TITLE
ticking entity

### ISSUE THREAD

**Issue by cowpod** [WildBamaBoy/minecraft-comes-alive#1030]
This occurred shortly after logging in to the world. No villagers in sight, or nearby, although I am in a village (no villagers on map).
I actually cannot understand what the crash log means, other than an entity error. It's possible that this error isn't MCA's fault, however as I believe it involves an MCA villager, I posted it here.
Minecraft Version: 1.12.2
MCA Version: 5.3.1
Full crash log is at the bottom.
`net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.world.World.func_72939_s(World.java:1770) ~[amu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112) ~[ActionProcreate.class:?]
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38) ~[ActionProcreate.class:?]
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90) ~[VillagerBehaviors.class:?]
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178) ~[EntityVillagerMCA.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	... 10 more
`
[crash-2018-05-22_17.10.01-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2029385/crash-2018-05-22_17.10.01-client.txt)

**Comment by cowpod** [comment]
seems to be another mod. closing
