### ISSUE TITLE
[1.12.2] MCA can spawn an invisible villager that spams the console when ExtraUtils2 is present

### ISSUE THREAD

**Issue by C0rn3j** [WildBamaBoy/minecraft-comes-alive#1073]
Console just spams this and the villager is invisible except for the name. Upon walking into him the screen turns white.

Save file (villager is right in front on the bridge): https://cloud2.rys.pw/s/9ntq79NgQ2mxjC8

Mod combination:
```
MCA-1.12.x-5.3.1-universal
RadixCore-1.12.x-2.2.1-universal
extrautils2-1.12-1.8.5
```

Original modlist - https://haste.rys.pw/raw/dixojagiwe

Forge: 14.23.4.2758
EDIT: Looks like Forge 2759 fixes the white screen issue. The invisible villager + massive logspam is still there though.
```
[20:23:37] [main/ERROR] [minecraft/RenderLivingBase]: Couldn't render entity
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:95) ~[cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) ~[cdr.class:?]
	at mca.client.model.ModelHuman.func_78088_a(ModelHuman.java:54) ~[ModelHuman.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_77036_a(RenderLivingBase.java:250) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:156) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41) [caf.class:?]
	at mca.client.render.RenderVillagerMCA.doRenderEntity(RenderVillagerMCA.java:133) [RenderVillagerMCA.class:?]
	at mca.client.render.RenderVillagerMCA.doRender(RenderVillagerMCA.java:366) [RenderVillagerMCA.class:?]
	at mca.client.render.RenderVillagerMCA.func_76986_a(RenderVillagerMCA.java:34) [RenderVillagerMCA.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:672) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:197) ~[cdt.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) ~[cdr.class:?]
	... 31 more
```

**Comment by marcell123455** [comment]
i also had invisible childs after i choosed "i have a family" but no error..

**Comment by C0rn3j** [comment]
@marcell123455 Keep in mind the error is a client log, not server log.
