### ISSUE TITLE
The game crash when a zombie infects a villager with a bricklayer's profession.

### ISSUE THREAD

**Issue by CucoML17** [WildBamaBoy/minecraft-comes-alive#1104]
Hello, 
when I am playing and a zombie approaches a villager with the profession of a bricklayer or fighter, at the moment of infecting the villager, the game crash.

Reading the error report, I noticed the cause of this problem, which is as follows; Minecraft seems to only have 5 villagers' prophecies with their respective ids, MCA added many more, which requires ids, causing when a villager with unregistered id is infected, the game is closed by skipping the following report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/26/19 7:12 PM
Description: Ticking entity

java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: 15 null
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:346)
	at net.minecraft.entity.monster.EntityZombieVillager.func_184206_a(EntityZombieVillager.java:319)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(SourceFile:125)
	at net.minecraft.entity.monster.EntityZombieVillager.func_190733_a(EntityZombieVillager.java:55)
	at net.minecraft.entity.monster.EntityZombie.func_70074_a(EntityZombie.java:409)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1172)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:536)
	at mca.entity.EntityVillagerMCA.func_70645_a(EntityVillagerMCA.java:262)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:294)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAIZombieAttack.func_75246_d(SourceFile:28)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:346)
	at net.minecraft.entity.monster.EntityZombieVillager.func_184206_a(EntityZombieVillager.java:319)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(SourceFile:125)
	at net.minecraft.entity.monster.EntityZombieVillager.func_190733_a(EntityZombieVillager.java:55)
	at net.minecraft.entity.monster.EntityZombie.func_70074_a(EntityZombie.java:409)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1172)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:536)
	at mca.entity.EntityVillagerMCA.func_70645_a(EntityVillagerMCA.java:262)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:294)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAIZombieAttack.func_75246_d(SourceFile:28)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
	Entity ID: 17253
	Entity Name: Zombi
	Entity's Exact location: -153.11, 72.00, -407.53
	Entity's Block location: World: (-154,72,-408), Chunk: (at 6,4,8 in -10,-26; contains blocks -160,0,-416 to -145,255,-401), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: -0.05, -0.08, -0.13
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Mundo nuevosdfg
	All players: 1 total; [EntityPlayerMP['carlosml17'/92, l='Mundo nuevosdfg', x=-146.51, y=72.53, z=-408.60]]
	Chunk stats: ServerChunkCache: 306 Drop: 0
	Level seed: 5034382136069947840
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,70*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (-143,4,-377), Chunk: (at 1,0,7 in -9,-24; contains blocks -144,0,-384 to -129,255,-369), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 19106 game time, 3098 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 110168 (now: false), thunder time: 39345 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 703154832 bytes (670 MB) / 1006632960 bytes (960 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                     | Version      | Source                               | Signature                                |
	|:--------- |:---------------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft              | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp                    | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML                    | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                  | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | radixcore              | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| UCHIJAAAA | mca                    | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar       | None                                     |
	| UCHIJAAAA | rezombiesv15ver1122jar | 1.5          | Re-Zombies-V1.5-Ver-1.12.2.jar       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['carlosml17'/92, l='Mundo nuevosdfg', x=-146.51, y=72.53, z=-408.60]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by HentaiHamster** [comment]
same thing happened to me except the villagers were bakers. 

here 

https://pastebin.com/7bYfPepJ
