### ISSUE TITLE
Server And Game Crashes When Near A Village

### ISSUE THREAD

**Issue by Rambut** [WildBamaBoy/minecraft-comes-alive#1120]
Would like to see a new update so servers can run this mod without crashing, 

Error Log

[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.entity.VillagerAttributes
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionSleep
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionSleep
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionSleep
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionFollow
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionProcreate
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionUpdateMood
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.AbstractToggleAction
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.AbstractToggleAction
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionCombat
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionCombat
[17:46:11] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager]: defineId called for: class mca.entity.EntityVillagerMCA from class mca.actions.ActionCombat
[17:46:14] [Netty Server IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_201]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_201]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_201]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by mightyjaffa12** [comment]
Does anyone actually work on this anymore?
