### ISSUE TITLE
Client loads, Server crashes.

### ISSUE THREAD

**Issue by AngelWing314** [WildBamaBoy/minecraft-comes-alive#1131]
Hey, I encountered some problems. I think this is a really great mod and I don't wanna skip it so easily. Anyhow, first problem was on your official site. When trying to download the file from there it give an " server error 500 ". ( this wasn't the real issue since I could download form curse forge but I wanted to let you know c: )The second was, my minecraft client boots up in a normal way, but when I try to run the server it crashes at some point while loading. Fairly close to the start, I don't think it even gets to loading the world. (I deleted the world file so it creates a new one while loading )I'm gonna include the server crash log in the if it can help you figure it out in any way. 
I'm on forge 14.23.5.2838 minecraft 1.12.2.

[crash-2019-06-02_08.14.02-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/3244482/crash-2019-06-02_08.14.02-server.txt)

**Comment by WildBamaBoy** [comment]
Try Forge 1.12.2-14.23.0.2491 with only MCA installed. Odd that a normally included library isn't found. Could have been removed in the later version of Forge you're using.

**Comment by SpeakerHornet** [comment]
-Forge 1.12.2-14.23.0.2491
-Clean install
-Freezes on load
-https://paste.ee/p/tgFZW

**Comment by WildBamaBoy** [comment]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source) ~[?:1.8.0_211]
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source) ~[?:1.8.0_211]
	at java.lang.AbstractStringBuilder.append(Unknown Source) ~[?:1.8.0_211]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.crash.CrashReportCategory.func_85072_a(CrashReportCategory.java:180) ~[c.class:?]
	at net.minecraft.crash.CrashReport.func_71506_a(CrashReport.java:160) ~[b.class:?]
	at net.minecraft.crash.CrashReport.func_71502_e(CrashReport.java:229) ~[b.class:?]
	at net.minecraft.client.Minecraft.func_71377_b(Minecraft.java:759) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:383) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 14 more

Give it a bit more memory on startup.

**Comment by WildBamaBoy** [comment]
#1132
