### ISSUE TITLE
Zombie Villagers are missing texture

### ISSUE THREAD

**Issue by praecipitator** [WildBamaBoy/minecraft-comes-alive#1149]
Zombie Villagers render with a broken texture, with this in the log:
[19:37:04] [Client thread/WARN] [net.minecraft.client.renderer.texture.TextureManager]: Failed to load texture: mca:textures/skins/
java.io.FileNotFoundException: mca:textures/skins/

Seems like the path hasn't been updated for v6. I tried copying assets\mca\textures\skins from the old jar to the new one as a workaround. The result was that only some worked, others only got the shadow, and the log was spammed with 
```
[19:48:51] [Client thread/ERROR] [net.minecraft.client.renderer.entity.RenderLivingBase]: Couldn't render entity
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:95) ~[cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44) ~[cdr.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:101) ~[bzg.class:?]
	at net.minecraft.client.renderer.entity.Render.func_180548_c(SourceFile:96) ~[bzg.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_77036_a(RenderLivingBase.java:240) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:175) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:197) ~[cdt.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69) ~[cdr.class:?]
	... 22 more
```

**Comment by praecipitator** [comment]
Screenshot:

![2019-06-12_19 37 11](https://user-images.githubusercontent.com/8077005/59374487-394eb080-8d4c-11e9-847c-bb800971a1d1.png)

**Comment by Hayran** [comment]
Same problem here!
