### ISSUE TITLE
The game crashed whilst ticking entity Error: java.lang.ClassCastException: mca.entity.EntityVillagerMCA cannot be cast to net.minecraft.entity.player.EntityPlayerMP Código de error: -1

### ISSUE THREAD

**Issue by TheWispper** [WildBamaBoy/minecraft-comes-alive#1329]
**Describe the bug**

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Launch Minecraft
2. Create a World
3. Then when I arrive at the village it crashes and down here you have the report.
Here is my report 👍 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.17_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  LoadingPlugin (BloodMoon-Mod-1.12.2.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.1-core.jar)
  CraftDevLoadingPlugin (craftdev-core-1.12.2-2.2.8.jar)
  LoadingPlugin (BetterWithLib-1.12-1.5.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/26/20 7:30 PM
Description: Ticking entity

java.lang.ClassCastException: mca.entity.EntityVillagerMCA cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.dmonsters.ai.EntityAITopielecAttack.func_75250_a(EntityAITopielecAttack.java:32)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.dmonsters.ai.EntityAITopielecAttack.func_75250_a(EntityAITopielecAttack.java:32)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: dmonsters:topielec (com.dmonsters.entity.EntityTopielec)
	Entity ID: 43066
	Entity Name: Topielec
	Entity's Exact location: -1166.19, 61.23, 568.06
	Entity's Block location: World: (-1167,61,568), Chunk: (at 1,3,8 in -73,35; contains blocks -1168,0,560 to -1153,255,575), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Entity's Momentum: 0.02, -0.01, -0.20
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: CumCraft-
	All players: 2 total; [EntityPlayerMP['TheWispper'/6177, l='CumCraft-', x=-1200.57, y=74.00, z=541.41], EntityPlayerMP['Requeson10'/42584, l='CumCraft-', x=-1203.11, y=74.00, z=541.45]]
	Chunk stats: ServerChunkCache: 1119 Drop: 0
	Level seed: -928463481349258160
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (216,64,248), Chunk: (at 8,4,8 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7395 game time, 7395 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 166849 (now: false), thunder time: 25070 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2693191952 bytes (2568 MB) / 5301600256 bytes (5056 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 108 mods loaded, 108 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                     | Version                | Source                                                 | Signature                                |
	|:------ |:---------------------- |:---------------------- |:------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft              | 1.12.2                 | minecraft.jar                                          | None                                     |
	| LCHIJA | mcp                    | 9.42                   | minecraft.jar                                          | None                                     |
	| LCHIJA | FML                    | 8.0.99.99              | forge-1.12.2-14.23.5.2854.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                  | 14.23.5.2854           | forge-1.12.2-14.23.5.2854.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy      | 1.0.0                  | minecraft.jar                                          | None                                     |
	| LCHIJA | itemphysic             | 1.4.0                  | minecraft.jar                                          | None                                     |
	| LCHIJA | foamfixcore            | 7.7.4                  | minecraft.jar                                          | None                                     |
	| LCHIJA | securitycraft          | v1.8.9                 | [1.12.2]+SecurityCraft+v1.8.9.jar                      | None                                     |
	| LCHIJA | ambientsounds          | 2.0.0                  | AmbientSounds_v2.3_mc1.12.2.jar                        | None                                     |
	| LCHIJA | baubles                | 1.5.2                  | Baubles-1.12-1.5.2.jar                                 | None                                     |
	| LCHIJA | astralsorcery          | 1.10.3                 | astralsorcery-1.12.2-1.10.3.jar                        | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | backpacks16840         | 3.5.4                  | backpacks+1.12.2+-+3.5.4.jar                           | None                                     |
	| LCHIJA | mcmultipart            | 2.5.3                  | MCMultiPart-2.5.3.jar                                  | None                                     |
	| LCHIJA | redstoneflux           | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar                | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| LCHIJA | sonarcore              | 5.0.16                 | sonarcore-1.12.2-5.0.16-16.jar                         | None                                     |
	| LCHIJA | bagelsmore             | 2.0.1                  | bagelsmore-1.12.2-2.0.1.jar                            | None                                     |
	| LCHIJA | betterthanllamas       | 1.12.1-1.0.0           | BetterThanLlamas-1.12.1-1.0.0.jar                      | None                                     |
	| LCHIJA | betterwithlib          | ${version}             | BetterWithLib-1.12-1.5.jar                             | None                                     |
	| LCHIJA | bibliotheca            | 1.3.3-1.12.2           | bibliotheca-1.3.3-1.12.2.jar                           | None                                     |
	| LCHIJA | bloodmoon              | 1.5.2                  | BloodMoon-Mod-1.12.2.jar                               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf              | 2.3.568                | Bookshelf-1.12.2-2.3.568.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | zawa                   | 1.12.2-1.4.0           | zawa+-+1.4.0+(1.12.2).jar                              | None                                     |
	| LCHIJA | bookworm               | 1.12.2-1.0.0           | bookworm+-+1.0.0+(1.12.2).jar                          | None                                     |
	| LCHIJA | jei                    | 4.13.1.225             | jei_1.12.2-4.13.1.225.jar                              | None                                     |
	| LCHIJA | botania                | r1.10-363              | Botania+r1.10-363.jar                                  | None                                     |
	| LCHIJA | codechickenlib         | 3.2.2.354              | CodeChickenLib-1.12.2-3.2.2.354-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | brandonscore           | 2.4.7                  | BrandonsCore-1.12.2-2.4.7.189-universal.jar            | None                                     |
	| LCHIJA | campfire               | 1.2                    | campfire-1.12-v1.2.jar                                 | None                                     |
	| LCHIJA | cavern                 | 1.10.6                 | Cavern_1.12.2-v1.10.6.jar                              | None                                     |
	| LCHIJA | chameleon              | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                               | None                                     |
	| LCHIJA | chesttransporter       | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar                      | None                                     |
	| LCHIJA | craftdevcore           | 2.2.8                  | craftdev-core-1.12.2-2.2.8.jar                         | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| LCHIJA | creativecore           | 1.9.9                  | CreativeCore_v1.9.35_mc1.12.2.jar                      | None                                     |
	| LCHIJA | cw                     | 1.0.2                  | creature_whisperer_1.0.2.jar                           | None                                     |
	| LCHIJA | cyclopscore            | 0.11.11                | CyclopsCore-1.12.2-0.11.11.jar                         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dmonsters              | 1.7                    | Deadly+Monsters+1.71.jar                               | None                                     |
	| LCHIJA | disenchanter           | 1.6                    | disenchanter-[1.12]1.6.jar                             | None                                     |
	| LCHIJA | dldungeonsjbg          | 1.13.2                 | DoomlikeDungeons-1.13.2-MC1.12.2.jar                   | None                                     |
	| LCHIJA | draconicevolution      | 2.3.17                 | Draconic-Evolution-1.12.2-2.3.17.321-universal.jar     | None                                     |
	| LCHIJA | eleccore               | 1.8.434                | ElecCore-1.12.2-1.8.434.jar                            | None                                     |
	| LCHIJA | mcjtylib_ng            | 3.0.7                  | mcjtylib-1.12-3.0.7.jar                                | None                                     |
	| LCHIJA | elementaldimensions    | 0.3.1                  | elementaldimensions-1.12-0.3.1.jar                     | None                                     |
	| LCHIJA | energeticsheep         | 1.1.3                  | EnergeticSheep-1.12.2-1.1.3.jar                        | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | erebus                 | 1.0.31                 | Erebus-1.0.31.jar                                      | None                                     |
	| LCHIJA | exoticbirds            | 1.0                    | Exotic+Birds+1.12.2-3.2.0.jar                          | None                                     |
	| LCHIJA | fairylights            | 2.1.5                  | fairylights-2.1.5-1.12.2.jar                           | None                                     |
	| LCHIJA | fbp                    | 2.4.1                  | FancyBlockParticles-1.12.x-2.4.1.jar                   | None                                     |
	| LCHIJA | fenceoverhaul          | 1.3.4                  | FenceOverhaul-1.3.4.jar                                | None                                     |
	| LCHIJA | ftfloocraft            | 1.9.3                  | Floocraft+1.12.2-1.9.3.jar                             | None                                     |
	| LCHIJA | foamfix                | 0.10.3-1.12.2          | foamfix-0.10.3-1.12.2.jar                              | None                                     |
	| LCHIJA | gargoyles              | 1                      | Gargoyles+mod+1.12.2+patch+1.jar                       | None                                     |
	| LCHIJA | mobtotems              | 1.12.1-0.3.0           | mobtotems-1.12.1-0.3.0.jar                             | None                                     |
	| LCHIJA | guideapi               | 1.12-2.1.8-63          | Guide-API-1.12-2.1.8-63.jar                            | None                                     |
	| LCHIJA | hammertime             | 2.2.0                  | Hammer+Time-2.2.0-1.12.2.jar                           | None                                     |
	| LCHIJA | harshenuniverse        | 0.22.12                | HarshenUniverse-0.22.12.jar                            | None                                     |
	| LCHIJA | howlingmoon            | 0.9                    | howlingmoon-1.12.2-0.9.jar                             | None                                     |
	| LCHIJA | huntingdim             | 1.0.36                 | HuntingDimension-1.12.2-1.0.36.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waila                  | 1.8.26                 | Hwyla-1.8.26-B41_1.12.2.jar                            | None                                     |
	| LCHIJA | infernalmobs           | 1.7.5                  | InfernalMobs-1.12.2.jar                                | None                                     |
	| LCHIJA | ironbackpacks          | 1.12.2-3.0.8-12        | IronBackpacks-1.12.2-3.0.8-12.jar                      | None                                     |
	| LCHIJA | jeiintegration         | 1.5.1.36               | jeiintegration_1.12.2-1.5.1.36.jar                     | None                                     |
	| LCHIJA | journeymap             | 1.12.2-5.5.3           | journeymap-1.12.2-5.5.3.jar                            | None                                     |
	| LCHIJA | jeresources            | 0.8.7.41               | JustEnoughResources-1.12.2-0.8.7.41.jar                | None                                     |
	| LCHIJA | malisiscore            | 1.12.2-6.4.0           | malisiscore-1.12.2-6.4.0.jar                           | None                                     |
	| LCHIJA | malisisdoors           | 1.12.2-7.3.0           | malisisdoors-1.12.2-7.3.0.jar                          | None                                     |
	| LCHIJA | radixcore              | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                   | None                                     |
	| LCHIJA | mca                    | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal (1).jar                     | None                                     |
	| LCHIJA | minecolonies           | 1.12.2-0.10.53-BETA    | minecolonies-1.12.2-0.10.53-BETA-universal.jar         | None                                     |
	| LCHIJA | moon-core              | 7.0                    | moon-core+7.0+(1.12).jar                               | None                                     |
	| LCHIJA | naturescompass         | 1.5.1                  | NaturesCompass-1.12.2-1.5.1.jar                        | None                                     |
	| LCHIJA | netherportalfix        | 5.3.17                 | NetherPortalFix_1.12.1-5.3.17.jar                      | None                                     |
	| LCHIJA | nice                   | 0.3.1                  | nice-1.12-0.3.1.jar                                    | None                                     |
	| LCHIJA | nightmares             | 1.0.10                 | Nightmares-1.12.2-1.0.10.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | noel                   | 1.0                    | noel-1.12.2-1.0.2.jar                                  | None                                     |
	| LCHIJA | recipehandler          | 0.12                   | NoMoreRecipeConflict-0.12(1.12.2).jar                  | None                                     |
	| LCHIJA | nei                    | 2.4.2                  | NotEnoughItems-1.12.2-2.4.2.240-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | nuclearcraft           | 2.16e                  | NuclearCraft-2.16e-1.12.2.jar                          | None                                     |
	| LCHIJA | progressivebosses      | 1.5.4                  | ProgressiveBosses-1.5.4-mc1.12.x.jar                   | None                                     |
	| LCHIJA | quickleafdecay         | 1.2.4                  | QuickLeafDecay-MC1.12.1-1.2.4.jar                      | None                                     |
	| LCHIJA | rezombiesv15ver1122jar | 1.5                    | Re-Zombies-V1.5-Ver-1.12.2.jar                         | None                                     |
	| LCHIJA | corerm                 | 1.3.1                  | RikMuldsCore_1.3.1.jar                                 | None                                     |
	| LCHIJA | ropebridge             | 2.0.5                  | ropebridge-1.12-2.0.7.jar                              | None                                     |
	| LCHIJA | ruins                  | 17.2                   | Ruins-1.12.2.jar                                       | None                                     |
	| LCHIJA | rustic                 | 1.0.13                 | rustic-1.0.13.jar                                      | None                                     |
	| LCHIJA | sereneseasons          | 1.2.18                 | SereneSeasons-1.12.2-1.2.18-universal.jar              | None                                     |
	| LCHIJA | spartanshields         | 1.4.1                  | SpartanShields-1.12.2-1.4.1.jar                        | None                                     |
	| LCHIJA | spookycraft            | 1.0.3                  | spookycraft-1.12.2-1.0.3.jar                           | None                                     |
	| LCHIJA | storagedrawers         | 1.12-5.3.5             | StorageDrawers-1.12.2-5.3.7.jar                        | None                                     |
	| LCHIJA | structpro              | 4.0                    | structpro-4.0-1.12.1.jar                               | None                                     |
	| LCHIJA | switchbow              | 1.5.5                  | switchbow-1.5.5-1.12.2.jar                             | None                                     |
	| LCHIJA | teletoro               | 1.12.2-26              | teletoro-1.12.2-26.jar                                 | None                                     |
	| LCHIJA | camping                | 2.4.2                  | TheCampingMod_2.4.2.jar                                | None                                     |
	| LCHIJA | thutcore               | 5.19.9                 | thutcore-1.12.2-5.19.9.jar                             | None                                     |
	| LCHIJA | thutcore_compat        | 1.0                    | thutcore-1.12.2-5.19.9.jar                             | None                                     |
	| LCHIJA | thuttech               | 6.1.5                  | thuttech-1.12.2-6.1.5.jar                              | None                                     |
	| LCHIJA | totemdefender          | 2.9                    | TotemDefender-1.12.2-2.9.jar                           | None                                     |
	| LCHIJA | tropicraft             | 7.1.8.105              | tropicraft-MC1.12.2-7.1.8.105.jar                      | None                                     |
	| LCHIJA | twilightforest         | 3.11.1021              | twilightforest-1.12.2-3.11.1021-universal.jar          | None                                     |
	| LCHIJA | waterstrainer          | 3.2.0                  | WaterStrainer-1.12-3.2.0.jar                           | None                                     |
	| LCHIJA | wawla                  | 2.5.264                | Wawla-1.12.2-2.5.264.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | drplibrary             | 1.12.2-0.1.3-pre       | drplibrary-1.12.2-0.1.2.4-SNAPSHOT-20181115.112433.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmblueprints        | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                       | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmmaarg             | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.014036.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmguis              | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.060253.jar    | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcore                | 1.12.2-0.4.6.2         | drpcore-1.12.2-0.4.6.2.jar                             | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmlocks             | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.051203.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpmedieval            | 1.12.2-0.2.8-pre2      | drpmedieval-1.12.2-0.2.8-pre2.jar                      | None                                     |
	| LCHIJA | thebetweenlands        | 3.4.1                  | TheBetweenlands-3.4.1-universal.jar                    | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
  
AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.17_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
LoadingPlugin (BloodMoon-Mod-1.12.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
BCModPlugin (backpacks+1.12.2+-+3.5.4.jar)
  brad16840.core.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.1-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
CraftDevLoadingPlugin (craftdev-core-1.12.2-2.2.8.jar)
  core.upcraftlp.craftdev.asm.CraftDevClassTransformer
LoadingPlugin (BetterWithLib-1.12-1.5.jar)
  betterwithmods.library.core.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 2 / 8; [EntityPlayerMP['TheWispper'/6177, l='CumCraft-', x=-1200.57, y=74.00, z=541.41], EntityPlayerMP['Requeson10'/42584, l='CumCraft-', x=-1203.11, y=74.00, z=541.45]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ScoutTheSaneless** [comment]
I also experience this, however, it happens whenever i spawn an MCA villager

**Comment by ScoutTheSaneless** [comment]
when im in singleplayer the whole world just flickers

**Comment by boredhero** [comment]
@TheWispper @ChaosDogG It looks to me like the issue is being caused the Deadly Monsters mod, specifically this class file [here](https://github.com/bigbang87/deadly-monsters/blob/master/forge-1.12.2/src/main/java/com/dmonsters/ai/EntityAITopielecAttack.java#L32) on Line 32 with the casting. Try and report this issue on their issue queue [here](https://github.com/bigbang87/deadly-monsters/issues) and close this issue. 

Note that at the top of the stacktrace:
```at com.dmonsters.ai.EntityAITopielecAttack.func_75250_a(EntityAITopielecAttack.java:32)```
