### ISSUE TITLE
Minecraft crashes with MCA 5.0.2 installed. (My crash report)

### ISSUE THREAD

**Issue by MaxoutExtre** [WildBamaBoy/minecraft-comes-alive#326]
[16:50:32] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:50:32] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:50:32] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[16:50:32] [main/INFO] [FML]: Forge Mod Loader version 7.10.130.1395 for Minecraft 1.7.10 loading
[16:50:32] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_40, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_40
[16:50:33] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:50:33] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:50:33] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:50:33] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:50:33] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:50:33] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:50:33] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:50:37] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:50:37] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:50:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:50:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:50:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:50:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:50:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:50:38] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[16:50:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[16:50:38] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:50:40] [main/INFO]: Setting user: Maxout_Extre
[16:50:43] [Client thread/INFO]: LWJGL Version: 2.9.1
[16:50:45] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:100]: ---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/25/15 4:50 PM
Description: Loading screen debug info

java.lang.Throwable
	at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:99)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:190)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 122245304 bytes (116 MB) / 193449984 bytes (184 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3958' Renderer: 'Intel(R) HD Graphics 4000'
[16:50:45] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[16:50:45] [Client thread/INFO] [FML]: MinecraftForge v10.13.3.1395 Initialized
[16:50:45] [Thread-7/INFO] [FML]: loc: minecraft:textures/font/ascii.png, i: 0, j: 0, size: 128, width: 128, height: 128
[16:50:45] [Thread-7/INFO] [FML]: loc: minecraft:textures/gui/title/mojang.png, i: 0, j: 0, size: 256, width: 256, height: 256
[16:50:45] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[16:50:45] [Client thread/INFO] [FML]: Preloading CrashReport classes
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.World$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.World$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.World$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.World$4
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.chunk.Chunk$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.entity.EntityTracker$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.entity.player.InventoryPlayer$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$4
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$5
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.network.NetHandlerPlayServer$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.network.NetworkSystem$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$1
[16:50:45] [Thread-7/INFO] [FML]: loc: fml:textures/gui/forge.png, i: 0, j: 0, size: 128, width: 128, height: 128
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$4
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$5
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$6
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$7
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$8
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$9
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$4
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$5
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$6
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$7
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$8
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$9
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$10
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$11
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$12
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$13
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$14
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$15
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$4
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$4
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.RenderGlobal$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$3
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$4
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureAtlasSprite$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureManager$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$1
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$2
[16:50:45] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$3
[16:50:45] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[16:50:46] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[16:50:46] [Client thread/INFO] [FML]: Searching C:\Users\Eshaan Hegde\AppData\Roaming\.minecraft\mods for mods
[16:50:46] [Client thread/INFO] [FML]: Also searching C:\Users\Eshaan Hegde\AppData\Roaming\.minecraft\mods\1.7.10 for mods
[16:50:52] [Client thread/INFO] [FML]: Forge Mod Loader has identified 7 mods to load
[16:50:52] [Client thread/INFO] [FML]: FML has found a non-mod file CodeChickenLib-1.7.10-1.1.3.136-universal.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[16:50:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, MCA, RadixCore] at CLIENT
[16:50:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, NotEnoughItems, MCA, RadixCore] at SERVER
[16:50:54] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Minecraft Comes Alive, FMLFileResourcePack:RadixCore
[16:50:54] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[16:50:54] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[16:50:54] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[16:50:54] [Client thread/INFO] [RadixCore]: RadixCore version 2.0.1 is running from C:\Users\Eshaan Hegde\AppData\Roaming\.minecraft
[16:50:54] [Client thread/ERROR] [RadixCore]: NullPointerException while trying to read options.txt. Defaulting to English.
[16:50:55] [Client thread/INFO] [FML]: Applying holder lookups
[16:50:55] [Client thread/INFO] [FML]: Holder lookups applied
[16:50:55] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:50:55] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[16:50:55] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[16:50:55] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:50:56] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[16:50:56] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:50:56] [Sound Library Loader/INFO]: Sound engine started
[16:50:58] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[16:50:58] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[16:50:58] [Client thread/ERROR] [CodeChickenCore]: Unable to do mod description scrolling due to lack of stencil buffer
[16:50:59] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 7 mods
[16:50:59] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Minecraft Comes Alive, FMLFileResourcePack:RadixCore
[16:51:00] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[16:51:01] [Client thread/INFO]: Created: 512x256 textures/items-atlas
[16:51:01] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:51:01] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[16:51:01] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[16:51:01] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:51:01] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:51:01] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[16:51:01] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[16:51:01] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:51:01] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[16:51:02] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:51:02] [Sound Library Loader/INFO]: Sound engine started
[16:51:39] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[16:51:39] [Server thread/INFO]: Generating keypair
[16:51:39] [Server thread/INFO]: Converting map!
[16:51:39] [Server thread/INFO]: Scanning folders...
[16:51:39] [Server thread/INFO]: Total conversion count is 0
[16:51:39] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[16:51:39] [Server thread/INFO] [FML]: Applying holder lookups
[16:51:39] [Server thread/INFO] [FML]: Holder lookups applied
[16:51:40] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@621b398e)
[16:51:40] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@621b398e)
[16:51:40] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@621b398e)
[16:51:40] [Server thread/INFO]: Preparing start region for level 0
[16:51:41] [Server thread/INFO]: Preparing spawn area: 4%
[16:51:42] [Server thread/INFO]: Preparing spawn area: 10%
[16:51:43] [Server thread/INFO]: Preparing spawn area: 18%
[16:51:44] [Server thread/INFO]: Preparing spawn area: 26%
[16:51:45] [Server thread/INFO]: Preparing spawn area: 33%
[16:51:46] [Server thread/INFO]: Preparing spawn area: 41%
[16:51:47] [Server thread/INFO]: Preparing spawn area: 49%
[16:51:48] [Server thread/INFO]: Preparing spawn area: 57%
[16:51:49] [Server thread/INFO]: Preparing spawn area: 64%
[16:51:50] [Server thread/INFO]: Preparing spawn area: 70%
[16:51:51] [Server thread/INFO]: Preparing spawn area: 78%
[16:51:52] [Server thread/INFO]: Preparing spawn area: 86%
[16:51:53] [Server thread/INFO]: Preparing spawn area: 92%
[16:51:54] [Server thread/INFO]: Preparing spawn area: 98%
[16:51:55] [Server thread/INFO]: Changing view distance to 24, from 10
[16:51:56] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[16:51:56] [Netty IO #1/INFO] [FML]: Client protocol version 2
[16:51:56] [Netty IO #1/INFO] [FML]: Client attempting to join with 7 mods : CodeChickenCore@1.0.6.39,NotEnoughItems@1.0.4.99,FML@7.10.130.1395,RadixCore@2.0.1,Forge@10.13.3.1395,MCA@5.0.2,mcp@9.05
[16:51:56] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[16:51:56] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[16:51:56] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[16:51:56] [Server thread/INFO]: Maxout_Extre[local:E:ac0c5533] logged in with entity id 154 at (-50.5, 68.0, 249.5)
[16:51:56] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[16:51:56] [Server thread/INFO]: Maxout_Extre (formerly known as The_Punk) joined the game
[16:52:17] [Thread-16/INFO] [RadixCore]: Checking if updates available for Minecraft Comes Alive...

_____________________________________________________________________

P.S: This is when I created a new world. It was going well and was about to create it until it said, "Shutting down Internal Server.". It took too long so I just closed my Minecraft. There.

**Comment by WildBamaBoy** [comment]
Downgrade your version of Forge to the version ending in 1291. That's the recommended version to use with MCA.
