### ISSUE TITLE
Follow Me Command Crashes Game

### ISSUE THREAD

**Issue by PortedOasis** [WildBamaBoy/minecraft-comes-alive#385]
AIFollow.OnUpdateServer throws a NullPointerException, might need a try/catch or something.

**Comment by PortedOasis** [comment]
Crash Report:
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/9/15 10:06 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mca.ai.AIFollow.onUpdateServer(AIFollow.java:69)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:298)
	at net.minecraft.world.World.func_72866_a(World.java:1873)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1843)
	at net.minecraft.world.World.func_72939_s(World.java:1672)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:703)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.ai.AIFollow.onUpdateServer(AIFollow.java:69)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:298)
	at net.minecraft.world.World.func_72866_a(World.java:1873)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1843)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityHuman (mca.entity.EntityHuman)
	Entity ID: 4911
	Entity Name: Delina
	Entity's Exact location: -107.04, 74.12, 199.69
	Entity's Block location: -108.00,74.00,199.00 - World: (-108,74,199), Chunk: (at 4,4,7 in -7,12; contains blocks -112,0,192 to -97,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.00, 0.00, -0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1672)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: a
	All players: 1 total; [EntityPlayerMP['PortedOasis'/210, l='a', x=-114.70, y=75.00, z=193.30]]
	Chunk stats: ServerChunkCache: 456 Drop: 0
	Level seed: 3916976616030863941
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -220.00,64.00,124.00 - World: (-220,64,124), Chunk: (at 4,4,12 in -14,7; contains blocks -224,0,112 to -209,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 12665 game time, 12665 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 47845 (now: false), thunder time: 1871 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:703)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 125533704 bytes (119 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.37.1334 Minecraft Forge 11.14.1.1334 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{8.0.37.1334} [Forge Mod Loader] (forge-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{11.14.1.1334} [Minecraft Forge] (forge-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6b-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['PortedOasis'/210, l='a', x=-114.70, y=75.00, z=193.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by WildBamaBoy** [comment]
Repaired with latest MCA and RadixCore.
