### ISSUE TITLE
new 5.0.6beta for minecraft 1.8 crashed  on first run when opening an existing world

### ISSUE THREAD

**Issue by sheenwhiteman** [WildBamaBoy/minecraft-comes-alive#390]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/06/15 14:12
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at net.minecraft.util.ClassInheritanceMultiMap$2.computeNext(SourceFile:90)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at net.minecraft.world.World.func_175650_b(World.java:3119)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:952)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:117)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:112)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:126)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 154232200 bytes (147 MB) / 337440768 bytes (321 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.37.1334 Minecraft Forge 11.14.1.1334 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{8.0.37.1334} [Forge Mod Loader] (forge-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{11.14.1.1334} [Minecraft Forge] (forge-1.8-11.14.1.1334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6b-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by WildBamaBoy** [comment]
Duplicate.
