### ISSUE TITLE
In MP Would been the other player disconnected if a MCA NPC is in the near

### ISSUE THREAD

**Issue by ThNathan** [WildBamaBoy/minecraft-comes-alive#399]
(Minecraft 1.8 MCA 5.0.6.1-1.8;RC 2.0.3-1.8)
I wait a long time to play the mod with a Friend but ad first I would to try it out. It's works nice but than if i spawn a MCA-NPC the joiner (this one whats Joined the game) disconnected from the Game but the host play normal along. After that i try to connect and I been disconnected with the argument:

Connection Lost
A fatal error has occured, this connetion  is terminated

That all what I can say... I tried out but it isn't working. 

Maybe this here helps

17:20:36] [pool-2-thread-1/ERROR]: Signature is missing from textures payload
[17:20:46] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at mca.core.forge.EventHooksFML.clientTickEventHandler(EventHooksFML.java:135) ~[EventHooksFML.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_EventHooksFML_clientTickEventHandler_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:371) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2144) ~[bsu.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1021) ~[bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by ThNathan** [comment]
Minecraft 1.8

**Comment by WildBamaBoy** [comment]
Make sure you are using the recommended version of Forge, and if that doesn't seem to help, try on a new world.
