### ISSUE TITLE
Game crashes when adopting a baby.

### ISSUE THREAD

**Issue by WildBamaBoy** [WildBamaBoy/minecraft-comes-alive#400]
java.lang.NullPointerException: Exception in server tick loop
        at mca.packets.PacketInteract.processOnGameThread(PacketInteract.java:305)
        at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:158)
        at mca.core.forge.EventHooksFML.serverTickEventHandler(EventHooksFML.java:151)

**Comment by Nekkit** [comment]
I have the same problem, is there a fix? I did not understand how to decompile the file to make the change in WildBamaBoy's post.
