### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by wesborgman** [WildBamaBoy/minecraft-comes-alive#427]
How do I submit a crash report?

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 6/24/15 8:25 PM
Description: Initializing game

java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context)
	at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:246)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:198)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context)
	at org.lwjgl.opengl.WindowsContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.WindowsContextImplementation.create(WindowsContextImplementation.java:50)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
	at org.lwjgl.opengl.DrawableGL.createSharedContext(DrawableGL.java:77)
	at org.lwjgl.opengl.DrawableGL.createSharedContext(DrawableGL.java:41)
	at org.lwjgl.opengl.SharedDrawable.<init>(SharedDrawable.java:50)
	at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:239)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:246)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:198)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 92162976 bytes (87 MB) / 223248384 bytes (212 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8545 Release' Renderer: 'RADEON X600/X550 Series'
	Launched Version: 1.8-Forge11.14.3.1480
	LWJGL: 2.9.1
	OpenGL: RADEON X600/X550 Series GL version 2.1.8545 Release, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)

**Comment by wesborgman** [comment]
tried the same on a total of 4 computers tonight (2 work fine no issues and 2 crash - I think this may be a forge issue not MCA issue) here is the 2nd computer report..

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3
Time: 6/24/15 8:36 PM
Description: Initializing game
java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context)
at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:246)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:198)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context)
at org.lwjgl.opengl.WindowsContextImplementation.nCreate(Native Method)
at org.lwjgl.opengl.WindowsContextImplementation.create(WindowsContextImplementation.java:50)
at org.lwjgl.opengl.ContextGL.(ContextGL.java:132)
at org.lwjgl.opengl.DrawableGL.createSharedContext(DrawableGL.java:77)
at org.lwjgl.opengl.DrawableGL.createSharedContext(DrawableGL.java:41)
at org.lwjgl.opengl.SharedDrawable.(SharedDrawable.java:50)
at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:239)
... 10 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:246)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:198)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 114838664 bytes (109 MB) / 222924800 bytes (212 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: 
Loaded coremods (and transformers): 
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8545 Release' Renderer: 'Radeon X300/X550/X1050 Series'
Launched Version: 1.8-Forge11.14.3.1480
LWJGL: 2.9.1
OpenGL: Radeon X300/X550/X1050 Series GL version 2.1.8545 Release, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: ~~ERROR~~ NullPointerException: null
Profiler Position: N/A (disabled)

**Comment by QORTEC** [comment]
I cant be positive but I think that bug is connected to the new forge splash screen.
If it is the forge splash screen that’s causing the issue you can disable it as a temporary fix

To disable edit config/splash.properties

change
enabled=false #Default true

**Comment by QORTEC** [comment]
Yep, looking at the crash-log again (to me) it looks like its a forge splash screen issue.
You you can report the failure here: https://github.com/MinecraftForge/FML/issues/644

I hope this helps

**Comment by wesborgman** [comment]
Where do I find the config file... (Sorry I am new to this..)

**Comment by QORTEC** [comment]
Do you know where your mods folder is?
It should be right beside the mods folder (in the same directory).

Are you launching the game through the Mojang Minecraft Launcher or are you using a different launcher (e.g. Technic)?

**Comment by wesborgman** [comment]
![image](https://cloud.githubusercontent.com/assets/4306879/8345496/0d2f8718-1abe-11e5-96a5-22589d899775.png)

**Comment by wesborgman** [comment]
I am using Mojang Minecraft launcher

**Comment by QORTEC** [comment]
There should be a config folder there.

Can you go to the Mojang Minecraft launcher and click on edit profile (the one you use for modded)
And when the new window opens (Profile Editor) can you take a screenshot of it?

**Comment by wesborgman** [comment]
![image](https://cloud.githubusercontent.com/assets/4306879/8345554/b8edbe1c-1abe-11e5-9652-5b55e7b0fe16.png)

**Comment by wesborgman** [comment]
Here is same screen with Java setting visible 

![image](https://cloud.githubusercontent.com/assets/4306879/8345568/f9d1b2a8-1abe-11e5-99d7-624913b7e11d.png)

I tried running Forge 11.14.3.1446 but same errors

**Comment by QORTEC** [comment]
I was able to get it to launch without any issues. Its strange, the config folder should of been generated automatically.

1. go to your .minecraft folder
2. go make a new folder called **config**
3. download the config file (https://dl.dropboxusercontent.com/u/66449916/splash.properties)
4. place the file into the config folder

The file is a simple text file, you can open it with notepad

**Comment by QORTEC** [comment]
You could manually make the config file, but I'm sitting in front of a Linux computer so I cant give exact step by step instructions of how to do that.

**Comment by wesborgman** [comment]
thanks man. I will see what I can do.

**Comment by QORTEC** [comment]
Happy to help. If you still need help just ask, I will keep an eye on this issue.

**Comment by WildBamaBoy** [comment]
Closing this as it's not MCA.

**Comment by wesborgman** [comment]
Fixed it Thanks!! My 8 year old will be so excited when it is on his computer in the AM
