### ISSUE TITLE
The game crashes when you go on an exsisting world

### ISSUE THREAD

**Issue by AdamKingsStorms** [WildBamaBoy/minecraft-comes-alive#438]
When I went to my world with MCA 5.0.6 1.8, the game crashed when I entered the world.

Crash Report: 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
	at java.util.HashMap$KeyIterator.next(HashMap.java:828)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at net.minecraft.util.ClassInheritanceMultiMap$2.computeNext(SourceFile:90)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at net.minecraft.world.World.func_175650_b(World.java:3125)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:952)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:117)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:189)
	at net.minecraft.world.World.func_72964_e(World.java:304)
	at net.minecraft.world.World.func_175726_f(World.java:299)
	at net.minecraft.world.World.func_180495_p(World.java:836)
	at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:73)
	at net.minecraft.block.Block.func_180645_a(Block.java:428)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:454)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:695)

**Comment by WildBamaBoy** [comment]
Looks like your world is corrupted. Doesn't look like it's MCA's fault.
