### ISSUE TITLE
I am creating a modpack trying to use MCA 1.7.2 and it doesn‘t work.

### ISSUE THREAD

**Issue by JStilton** [WildBamaBoy/minecraft-comes-alive#458]
I am creating a modpack trying to use MCA 1.7.2 and it doesn‘t work. I was trying to use MCA 1.7.10 on 1.7.2 but still didn‘t work pls help me. Here is the crash report

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/13/15 4:19 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/radixshock/radixcore/core/IUpdateChecker
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:491)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(MinecraftOverlay.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(MinecraftOverlay.java:815)
	at net.minecraft.client.main.Main.main(SourceFile:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.radixshock.radixcore.core.IUpdateChecker
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 34 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:491)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(MinecraftOverlay.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(MinecraftOverlay.java:815)
	at net.minecraft.client.main.Main.main(SourceFile:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.2
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 82001520 bytes (78 MB) / 322076672 bytes (307 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 Optifine OptiFine_1.7.2_HD_U_D5 27 mods loaded, 27 mods active
	mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.2.217.1147} [Forge Mod Loader] (forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed
	Forge{10.12.2.1147} [Minecraft Forge] (forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed
	SC0_SpaceCore{0.7.3} [SpaceCore] (SpaceCore-1.7.2.jar) Unloaded->Constructed
	SC0_Wings{1.2.4} [Survival Wings] ([1.7.2] Survival Wings 1.2.4.zip) Unloaded->Constructed
	bspkrsCore{6.11} [bspkrsCore] ([1.7.2]bspkrsCore-universal-6.11.jar) Unloaded->Constructed
	Treecapitator{1.7.2} [Treecapitator] ([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed
	animalsPlus{1.2} [Animals+] (animalsPlus-1.2.jar) Unloaded->Constructed
	AnimationAPI{1.2.2} [AnimationAPI] (AnimationAPI-1.7.2-1.2.2.jar) Unloaded->Constructed
	babyanimals{1.7.10-2} [Baby Animals Model Swapper] (BabyAnimals-1.7.10-2.jar) Unloaded->Constructed
	BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft[v1.8.2][MC1.7.2].jar) Unloaded->Constructed
	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (BiomesOPlenty-1.7.2-2.0.2.932-universal.jar) Unloaded->Constructed
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed
	craftguide{1.5.2} [CraftGuide] (CraftGuide-1.6.8.0.zip) Unloaded->Constructed
	props{1.10} [Decocraft] (Decocraft-1.10_1.7.2and1.7.10.jar.zip) Unloaded->Constructed
	eplus{1.7.2-2.0.4} [Enchanting Plus] (EnchantingPlus-1.7.2-2.0.4.jar) Unloaded->Constructed
	fairymod{0.5} [Fairy Mod] (fairymod-0.5-1.7.2.jar) Unloaded->Constructed
	inventorytweaks{1.57-116} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.2.jar) Unloaded->Constructed
	lucky{4.5.0} [Lucky Block] (Lucky-Block-Mod-1.7.2.jar) Unloaded->Constructed
	radixcore{1.2.0} [RadixCore] (RadixCore-1.2.0 MC-1.7.2.zip) Unloaded->Constructed
	mca{4.1.2} [Minecraft Comes Alive] (MCA-4.1.2 MC-1.7.2.zip) Unloaded
	cfm{3.4.7} [ß9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.2).jar) Unloaded
	plantmegapack{3.00.05} [Plant Mega Pack] (Plant-Mega-Pack-Mod-1.7.2.jar) Unloaded
	RainbowWorld{1.0.0} [RainbowWorld] (Rainbow World (1.7.x).jar) Unloaded
	treeores{5.5} [treeores] (TreeOresMod-1.7.10-5.5.jar) Unloaded
	TwilightForest{2.2.3} [The Twilight Forest] (twilightforest-1.7.2-2.2.3.jar) Unloaded
	voxelmap{1.7.2} [VoxelMap] (voxelmap-1.7.2-1.0.jar) Unloaded
	Launched Version: 1.7.2
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.6.31, Intel Inc.
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
	Anisotropic Filtering: Off (1)

**Comment by makromoo** [comment]
Did you download radixcore, which is required for the mod to work?
Link for official 1.7.2 download can be found here: http://www.curse.com/mc-mods/minecraft/radixcore/2215263

**Comment by TheShootingStar45** [comment]
I see RadixCore have already been downloaded.
However, i saw there's some mod that aren't constructed, only unloaded.
Look up at Minecraft Comes Alive, the list shows that it only unloaded, isn't it?
If you use 1.7.2, use a matching download.
(Note that this list is the updated MCA downloads)
Minecraft Version: 1.7.2
Minecraft Comes Alive Version: 4.1.2
RadixCore Version: 1.2.0

For a clear, easy to track, neat-looking downloads, you can go to this official page:
http://www.radix-shock.com/mca--download.html

-TheShootingStar45

**Comment by JStilton** [comment]
-TheShootingStar45 I am using these versions you told me to do already but with the same result, what should I do?
![screen shot 2015-07-13 at 18 02 06](https://cloud.githubusercontent.com/assets/13253068/8654223/5dc87d68-2989-11e5-9ca0-44dfeab52baf.png)
![screen shot 2015-07-13 at 18 02 24](https://cloud.githubusercontent.com/assets/13253068/8654224/5dd4b61e-2989-11e5-8da4-fc992e8a2058.png)

**Comment by WildBamaBoy** [comment]
Do not post duplicates of your issue. Use MCA 5 on 1.7.10 and move away from 1.7.2. Any previous version is not supported.
