### ISSUE TITLE
Server crashes with World not created with MCA.

### ISSUE THREAD

**Issue by XanaRaquel** [WildBamaBoy/minecraft-comes-alive#460]
I'm trying to upgrade my vanilla 1.8 server to a forge with MCA server.
This is what I did:
- Created the new server with forge.
- Went in-game, everything ok. Closed everything.
- Deleted the new World folder and copied the World from the old server.
- Started the new server, went in-game, everthing is ok. I'm playing in the old World in the new server.
- Closed everything, copied MCA and RadixCore to the mod folder of the server.
- Started the new server and crash.

**This is the crash log:**
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 13-07-2015 19:54
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at net.minecraft.util.ClassInheritanceMultiMap$2.computeNext(SourceFile:90)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at net.minecraft.world.World.func_175650_b(World.java:3126)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:952)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:117)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:272)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:259)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2070143552 bytes (1974 MB) / 2416443392 bytes (2304 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xms2G -Xmx3G
	IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1446 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1446-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{11.14.3.1446} [Minecraft Forge] (forge-1.8-11.14.3.1446-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	RadixCore{2.0.3-1.8} [RadixCore] (RadixCore-2.0.3-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MCA{5.0.6.1-1.8} [Minecraft Comes Alive] (MCA-5.0.6.2-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 5; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**this is in the server console before the crash:**
[19:54:16] [Server thread/INFO] [FML]: Injecting itemstacks
[19:54:16] [Server thread/INFO] [FML]: Itemstack injection complete
[19:54:16] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[19:54:16] [Server thread/INFO]: Preparing level "TestAlive"
[19:54:17] [Server thread/INFO] [FML]: Loading dimension 0 (TestAlive) (net.minecraft.server.dedicated.DedicatedServer@24c5c4e8)
[19:54:17] [Server thread/INFO] [FML]: Loading dimension 1 (TestAlive)  (net.minecraft.server.dedicated.DedicatedServer@24c5c4e8)
[19:54:17] [Server thread/INFO] [FML]: Loading dimension -1 (TestAlive) (net.minecraft.server.dedicated.DedicatedServer@24c5c4e8)
[19:54:17] [Server thread/INFO]: Preparing start region for level 0
[19:54:18] [Server thread/INFO]: Preparing spawn area: 14%
[19:54:18] [Server thread/ERROR]: Encountered an unexpected exception java.util.ConcurrentModificationException

**Extra infos:**
Already run "Repair regions" from MCEdit and no bad regions.
The old world was created on a 1.8 vanilla server.
Already did these tests:
- New world generated = No crash.
- New world generated + MCA = No crash.
- Old world copied to new server = No crash.
- Old world copied to new server + MCA = Crash!

Any extra information just ask.
EDIT: Just noticed now that in the crash log it says I'm using MCA v5.0.6.1 which is false. I'm using MCA-5.0.6.2-1.8-universal.

**Comment by Hernan0708** [comment]
sometimes existing worlds do not work with forge or can conflict with some of your mods

**Comment by WildBamaBoy** [comment]
#467
