### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by QuadMercury** [WildBamaBoy/minecraft-comes-alive#468]
While playing on 1.8 forge server, I and the other player (we only play on the server, the 2 of us) get "Fatal error has occured" this happens a lot and only to the person that joins latest, not to the first one that joins. Sometimes the server also just stops reacting to anything you do, trying to interact with anything doesn't work, there are no sounds but the you don't get kicked. Once you click close to restart the game, MC "stops responding". (these crashes rarely happened when the mod came out for 1.8 and then the crashes started happening more and more) We also updated to the latest version today that should be server compatible but the crashes keep happening.

**Comment by WildBamaBoy** [comment]
I need a crash log, client log, something to diagnose a problem like this.

**Comment by QuadMercury** [comment]
[Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/wool_colored_light_gray.png
java.io.FileNotFoundException: minecraft:textures/blocks/wool_colored_light_gray.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:70) ~[cvc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[cvt.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:116) [cua.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83) [cua.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:91) [ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29) [cxk.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99) [cvt.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[16:56:19] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/.png
java.io.FileNotFoundException: minecraft:textures/.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:70) ~[cvc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[cvt.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:116) [cua.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83) [cua.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:91) [ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29) [cxk.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99) [cvt.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[16:56:19] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/torch.png
java.io.FileNotFoundException: minecraft:textures/blocks/torch.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:70) ~[cvc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[cvt.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:116) [cua.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:83) [cua.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:91) [ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29) [cxk.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99) [cvt.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325) [bsu.class:?]
	at net.minecraft.client.main.Main.main



This is the crash log for the Fatal Error. Unfortunately I was not able to find the other crash log for when the game stops responding to any actions since we haven't played MC in a long time and don't remember when it last happened (it doesn't happen much).

Thank you for your awesome work, keep it up !

**Comment by WildBamaBoy** [comment]
No relevant information in that log. It looks like it may have been cut off. Post it to pastebin.com and provide a link so that I can see the whole thing.

**Comment by QuadMercury** [comment]
I copy&pasted it again, now all of the information is there.

**Comment by QuadMercury** [comment]
Btw, we'll try and play some MC to see if we can cause the game stops responding problem tommowo so I could post the crash log for that since it's pretty late in the night right now.

**Comment by QuadMercury** [comment]
Game now stops responding to anything after few minutes of in-game time and closes without getting the "Not Responding" so I can't get a crash log.

**Comment by WildBamaBoy** [comment]
That just sounds like any sort of issue with your client. MCA doesn't do anything that could lock up the game like that, and without a crash log there's nothing I can do.
