### ISSUE TITLE
Help! Do I have to create a new world?

### ISSUE THREAD

**Issue by minerofobsidian** [WildBamaBoy/minecraft-comes-alive#501]
Alright, so I downloaded Radix-Core (neccesary to run MCA) and MCA, and I tried to open my world where I'm building a city (which is progressed A LOT), and the game crashed just after loading the world. For reference, there are a few things you need to know:
1) I have disabled the Overwrite Villagers option, but I'd rather not have to do that.
2) Other mods I have installed are:
     a) Forge
     b) Optifine
     c) Decoration Mega Pack
     d) Custom NPCs
     e) World edit
3) I have also made a new world and opened my old one after doing Number 1. Both worked.
And here is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 8/2/15 9:22 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at net.minecraft.util.ClassInheritanceMultiMap$2.computeNext(SourceFile:90)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at net.minecraft.world.World.func_175650_b(World.java:3126)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:952)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:117)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:183)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:206)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 85249392 bytes (81 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1499 Optifine OptiFine_1.8_HD_U_D5 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1499.jar) 
	UCHIJAAAAAAA	Forge{11.14.3.1499} [Minecraft Forge] (forge-1.8-11.14.3.1499.jar) 
	UCHIJAAAAAAA	customnpcs{1.8.0_beta} [CustomNpcs] (CustomNPCs_1.8.0_beta.jar) 
	UCHIJAAAAAAA	decorationmegapack{1.18} [Decoration Mega Pack] (decorationmegapack-1.18-1.8-1446.jar) 
	UCHIJAAAAAAA	RadixCore{2.0.3-1.8} [RadixCore] (RadixCore-2.0.3-1.8-universal.jar) 
	UCHIJAAAAAAA	MCA{5.0.6.1-1.8} [Minecraft Comes Alive] (MCA-5.0.6.2-1.8-universal.jar) 
	UCHIJAAAAAAA	worldedit{6.1} [WorldEdit] (worldedit-forge-mc1.8-6.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

This may be a bug, issue, or a screw up on my part. I don't know where else to put this, so I apologize if this is NOT where this should go, but could someone please help me with my problem? I want the mod to overwrite villagers, but not to have to make a new world...

**Comment by WildBamaBoy** [comment]
I'm not quite sure why this happens yet, but it is a known problem on existing worlds where MCA did not previously run.

**Comment by XanaRaquel** [comment]
Same problem as #467 and #460.

**Comment by WildBamaBoy** [comment]
Should be fixed in 8d7ab24bfb056e0261e2bfa231e20a2776598030.
