### ISSUE TITLE
Crash Report Couldn't Even Log On World

### ISSUE THREAD

**Issue by PrincessPeach08** [WildBamaBoy/minecraft-comes-alive#506]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/5/15 5:15 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mca.ai.AIFollow.onUpdateServer(AIFollow.java:69)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:298)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:695)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.ai.AIFollow.onUpdateServer(AIFollow.java:69)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:298)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityHuman (mca.entity.EntityHuman)
	Entity ID: 225
	Entity Name: Nicholas
	Entity's Exact location: -424.50, 72.00, 176.20
	Entity's Block location: -425.00,72.00,176.00 - World: (-425,72,176), Chunk: (at 7,4,0 in -27,11; contains blocks -432,0,176 to -417,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: The New World
	All players: 1 total; [EntityPlayerMP['PrincessPeach08'/223, l='The New World', x=-425.80, y=78.44, z=184.03]]
	Chunk stats: ServerChunkCache: 1586 Drop: 0
	Level seed: 1447711276
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 59.00,64.00,291.00 - World: (59,64,291), Chunk: (at 11,4,3 in 3,18; contains blocks 48,0,288 to 63,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 251166 game time, 257243 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 53992 (now: false), thunder time: 19531 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:695)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 191256752 bytes (182 MB) / 587005952 bytes (559 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	lucky{6.0.0} [Lucky Block] (LuckyBlock_1-8-3_v6-0-0-2) 
	UCHIJAAAA	RadixCore{2.0.3-1.8} [RadixCore] (RadixCore-2.0.3-1.8-universal.jar) 
	UCHIJAAAA	MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6b-1.8-universal.jar) 
	UCHIJAAAA	XaeroMinimap{1.5.7} [Xaero's Minimap] (xaeros_minimap_v1.5.7_1.8_Forge-2.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['PrincessPeach08'/223, l='The New World', x=-425.80, y=78.44, z=184.03]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by WildBamaBoy** [comment]
#497
