### ISSUE TITLE
Crash when it becomes night.

### ISSUE THREAD

**Issue by Rockpaw** [WildBamaBoy/minecraft-comes-alive#521]
Just downloaded the mod today, Im using forge 1.8-Forge11.14.3.1450, The only other mod I have installed is optifine, I have tried to play without it. I use the crystal ball to spawn a village, and when it gets close to night, the game crashes. If I try and load the map up, it crashes.
Here is the crash report I get.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 8/23/15 3:08 AM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=part, clazz=class net.minecraft.block.BlockBed$EnumPartType, values=[head, foot]} as it does not exist in BlockState{block=minecraft:cobblestone, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at mca.ai.AISleep.trySleepInBed(AISleep.java:354)
	at mca.ai.AISleep.onUpdateServer(AISleep.java:90)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:308)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:158)
	at mca.ai.AISleep.trySleepInBed(AISleep.java:354)
	at mca.ai.AISleep.onUpdateServer(AISleep.java:90)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:308)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityHuman (mca.entity.EntityHuman)
	Entity ID: 200
	Entity Name: Trent
	Entity's Exact location: -238.00, 70.00, 387.00
	Entity's Block location: -238.00,70.00,387.00 - World: (-238,70,387), Chunk: (at 2,4,3 in -15,24; contains blocks -240,0,384 to -225,255,399), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: Minecraft Alive
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1368767265
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -256.00,64.00,256.00 - World: (-256,64,256), Chunk: (at 0,4,0 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 12547 game time, 12547 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 37915 (now: false), thunder time: 113481 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141271024 bytes (134 MB) / 358920192 bytes (342 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 Optifine OptiFine_1.8_HD_U_D5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	RadixCore{1.8-2.0.4} [RadixCore] (RadixCore-1.8-2.0.4-universal.jar) 
	UCHIJAAAA	MCA{1.8-5.0.7} [Minecraft Comes Alive] (MCA-1.8-5.0.7-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by HillustratedMike36** [comment]
#522 and #523 also confirm this.

**Comment by WildBamaBoy** [comment]
Fixed in 1.8-5.0.7.1. https://github.com/WildBamaBoy/minecraft-comes-alive/pull/526
