### ISSUE TITLE
Unarchiving causes crash

### ISSUE THREAD

**Issue by kitsune309** [WildBamaBoy/minecraft-comes-alive#530]
Accidentally posted too soon, details to follow shortly

**Comment by kitsune309** [comment]
I'm on a mac running OS X Yosemite 10.10.5 running Minecraft 1.7.10 with Forge 10.13.4.1448


I canot compress things directly into a .jar, I have to compress it to .zip and then rename it. 
When I unarchive the MCA-1.7.10-5.0.7.2-universal.jar (I want to add custom skins for villagers, I wouldn’t mind having some of the names and dialogue edited too, but that’s secondary) and rearchive it, it crashes the game upon loading even if I haven’t made any edits to the file. If I leave it as .zip, the effect is the same. 

Biomes o’ Plenty is also on, but taking it off doesn’t fix the problem. 

Could tell me how to fix it? or I could give you the skins I want added and let you have at it. Your choice.

This is the Crash log:


cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: mca.core.MCA
at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mca.core.MCA
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:249)
at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
... 10 more
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Mac OS X (x86_64) version 10.10.5
Java Version: 1.6.0_65, Apple Inc.
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
Memory: 122292872 bytes (116 MB) / 262275072 bytes (250 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 6 mods loaded, 6 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
UC	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) 
UC	RadixCore{2.0.3} [RadixCore] (RadixCore-1.7.10-2.0.3-universal.jar) 
UE	MCA{1.7.10-5.0.7.2} [Minecraft Comes Alive] (MCA-1.7.10-5.0.7.2-universal.zip) 
GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.4.2 310.41.35f01' Renderer: 'NVIDIA GeForce GT 650M OpenGL Engine'

**Comment by HillustratedMike36** [comment]
You could try deleting your MCA and RadixCore config files.

**Comment by kitsune309** [comment]
Unfortunately, nothing changed. It still crashes when I un- and re-archive the file, regardless of whether I changed anything in it. 

It works fine from the one I leave alone, so the game's still playable, but it sucks that I can't add skins.

**Comment by HillustratedMike36** [comment]
@kitsune309 It does...but I'm guessing MCA is very delicate when it comes to modifying files, I guess...

You might want to close this now.

**Comment by kitsune309** [comment]
But it hasn't been fixed, and considering the thing I'm trying to do is a popular enough action to be on the FAQ page, I'd really prefer to leave it open until it is.

**Comment by WildBamaBoy** [comment]
This indicates you're not zipping up the JAR properly. When you open the newly zipped JAR, the first group of files should be: https://gyazo.com/5764326aff121897a4b90e2ac222d1b8
