### ISSUE TITLE
Minecraft Comes Alive / Ars Magica issue between village guards and Dark Mage running latest of both mods

### ISSUE THREAD

**Issue by chrom20** [WildBamaBoy/minecraft-comes-alive#576]
Can recreate multiple instances using creative as well as in world on server

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/7/15 4:33 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
	at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by BlueGolisano** [comment]
Ticking Entity might (MIGHT) be a bugged AI or your Java system got overloaded. NOTE I AM NOT PRO AT THIS!

**Comment by WildBamaBoy** [comment]
~~MCA version please~~

**Comment by WildBamaBoy** [comment]
No response, closing.
