### ISSUE TITLE
Server crashes when a villager is asked to create a farm (it's OK just running on client)

### ISSUE THREAD

**Issue by kpateman** [WildBamaBoy/minecraft-comes-alive#624]
Hi,

We really love this mod but it almost always crashes when we ask a villager to create a farm. It does sometimes work, but mostly we get the crash. This is true for the 1.8 version too.

I had just Radix core, MCA and Biomes O Plenty mods installed and the forge version was: forge-1.8.9-11.15.1.1731-universal.

Here is the crash report from a 1.8.9 server.

---- Minecraft Crash Report ----

Time: 04/02/16 15:38
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at mca.api.CropEntry.getCropName(CropEntry.java:87)
	at mca.ai.AIFarming.startFarming(AIFarming.java:341)
	at mca.packets.PacketToggleAI.processOnGameThread(PacketToggleAI.java:117)
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:164)
	at mca.core.forge.EventHooksFML.serverTickEventHandler(EventHooksFML.java:175)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_EventHooksFML_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:253)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:649)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
	Memory: 121189360 bytes (115 MB) / 259522560 bytes (247 MB) up to 259522560 bytes (247 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 100
	FML: MCP 9.19 Powered by Forge 11.15.1.1731 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1731-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1731} [Minecraft Forge] (forge-1.8.9-11.15.1.1731-universal.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1603-universal.jar) 
	UCHIJAAAA	RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
	UCHIJAAAA	MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.1.2-universal.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['DoodleyNoodley'/1480, l='ServerWorld', x=120.21, y=71.00, z=226.31]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by PyrxMagi** [comment]
I've had the same issue.

**Comment by waznor** [comment]
ey i have the same issue will this be looked into?

**Comment by UnstableCodeScarlet** [comment]
Issue now Occurring on 1.10.2
Re-Open good idea.

**Comment by Phonavis** [comment]
Better re-open this.
Same results, different cause on 1.10.2
http://puu.sh/r0Jz3/d7cb6716f7.txt

Figured since it was the same result, I should post here instead of creating a new issue.
Stupid auto-forum isn't very specific on criteria.
