### ISSUE TITLE
Librarian first-time right-click crash

### ISSUE THREAD

**Issue by ivan-petrovic-soprex** [WildBamaBoy/minecraft-comes-alive#633]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 2/15/16 8:07 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.entity.passive.EntityVillager$ListEnchantedBookForEmeralds.func_179401_a(EntityVillager.java:936)
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:575)
	at net.minecraft.entity.passive.EntityVillager.func_70934_b(EntityVillager.java:536)
	at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:757)
	at mca.packets.PacketInteract.processOnGameThread(PacketInteract.java:130)
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:164)
	at mca.core.forge.EventHooksFML.serverTickEventHandler(EventHooksFML.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_EventHooksFML_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:301)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 251170840 bytes (239 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 Optifine OptiFine_1.8_HD_U_D5 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAAAAAAA	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAAAAAAA	ChickenShed{1.1.4} [Chicken Shed] ([1.8] ChickenShed (v1.2.0).jar) 
	UCHIJAAAAAAAAA	antiqueatlas{4.2.6-1.8} [Antique Atlas] (antiqueatlas-4.2.6-1.8.jar) 
	UCHIJAAAAAAAAA	buffalo{1.0} [Bison Mod] (bisonmod.jar) 
	UCHIJAAAAAAAAA	CMDfiles{0} [CMDfiles] (CMD files.jar) 
	UCHIJAAAAAAAAA	cmd{1.8} [Custom Music Discs] (Custom Music Discs-1.8.jar) 
	UCHIJAAAAAAAAA	hopperducts{1.4.5} [Hopper Ducts] (hopperducts-mc1.8-1.4.5.jar) 
	UCHIJAAAAAAAAA	imc{1.9.0} [Improving Minecraft] (Improving Minecraft-1.9.0.jar) 
	UCHIJAAAAAAAAA	JEI{2.14.0.139} [Just Enough Items] (jei_1.8-2.14.0.139.jar) 
	UCHIJAAAAAAAAA	latticemod{1.1} [Lattice Mod] (latticemod-mc1.8-1.1.jar) 
	UCHIJAAAAAAAAA	RadixCore{1.8-2.0.5} [RadixCore] (RadixCore-1.8-2.0.5-universal.jar) 
	UCHIJAAAAAAAAA	MCA{1.8-5.0.7.1} [Minecraft Comes Alive] (MCA-1.8-5.0.7.1-universal.jar) 
	UCHIJAAAAAAAAA	CookYourFood{0.9} [Cook your food] (MF-CookYourFood-1.8--0.9beta.jar) 
	UCHIJAAAAAAAAA	NoPillaring{0.95dim} [Pillaring denied] (MF-PillaringDenied-1.8--0.99beta.jar) 
	UCHIJAAAAAAAAA	ropebridge{1.1} [Rope Bridge] (RopeBridge-v1.2-mc1.8.8.jar) 
	UCHIJAAAAAAAAA	SophisticatedWolves{3.6.0} [SophisticatedWolves] (SophisticatedWolves-3.6.0.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8-1.4.5.jar)
  net.fybertech.nwr.NowWithRendering
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['MoonFather'/79696, l='New World-', x=4398.12, y=66.00, z=-4094.32]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by WildBamaBoy** [comment]
Remove your other mods and reproduce the issue, then post again.
