### ISSUE TITLE
A lot villagers spawn and wont die [1.8-5.1.1.2]

### ISSUE THREAD

**Issue by kevin013** [WildBamaBoy/minecraft-comes-alive#639]
Hi,

I recently downloaded MCA for the server. we could build the first day, went to sleep and checked the next day, and the whole map was spread with villagers! 
I don't know what caused this, only that it is 100% from MCA.
We also know we didn't change the server at night and nobody else entered the server.
Killing them would not work, they would spawn immediately 
![2016-02-16_21 55 34](https://cloud.githubusercontent.com/assets/17319060/13150191/055e2f5e-d665-11e5-8bee-16e7984e3dd4.png)
At the first picture I had some mods installed, so i removed them al EXCEPT MCA and radix-core and it did not change. removing MCA would not work because the map would crash without a reason.
![2016-02-18_17 03 17](https://cloud.githubusercontent.com/assets/17319060/13150227/28f19596-d665-11e5-980c-6e1e6e19fc02.png)
I would really like to know how to fix this because now the map is corrupted and while running the server we get a lag drop to 1 fps and chunks won't load so it is very frustrating
![2016-02-18_17 02 57](https://cloud.githubusercontent.com/assets/17319060/13150229/28f9ca0e-d665-11e5-8c2c-a0579c5bb9d1.png)
We already checked the forums and GitHub but we could not find our problem, that's why i'm writing this right now.
We also tried to disable all mob spawn and than kill all entities but than it will crash because the amount of villagers.

Later on the day I will make a .zip of the world so you can see it by yourself.

![2016-02-18_17 03 03](https://cloud.githubusercontent.com/assets/17319060/13150230/290057d4-d665-11e5-9b32-f2bcd262b5a5.png)
![2016-02-18 2](https://cloud.githubusercontent.com/assets/17319060/13150401/ebbbeb76-d665-11e5-886e-2a89cd96afd4.png)
Sorry for causing trouble but thanks in advance and we hope we can fix this problem.
(pictures were made in singleplayer, but that doesn't change anything about the problem)

regards.

**Comment by kevin013** [comment]
https://onedrive.live.com/redir?resid=BFA2E736EE24632F!2351&authkey=!ANxNp2jupYBancI&ithint=file%2crar

Here is the map.

**Comment by WildBamaBoy** [comment]
Please provide the crash report from the server once it occurs.

**Comment by kevin013** [comment]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/19/16 6:39 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.WorldServer.func_180497_b(WorldServer.java:545)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:545)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:117)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:112)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:126)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 521753424 bytes (497 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAAAAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAAAAA	customnpcs{1.8.0} [CustomNPCs] (CustomNPCs_1.8.0(09jan16).jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by kevin013** [comment]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2/19/16 8:14 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.WorldServer.func_180497_b(WorldServer.java:545)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:545)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:117)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:112)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:126)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 363151824 bytes (346 MB) / 734158848 bytes (700 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by kevin013** [comment]
The upper comments show the report file when loading the map without MCA.
The report file under will show you while running MCA when the client get stuck after playing the map 3-5 minutes. 
Disabling mob from spawning by gamerule command and use /kill @e[type=!Player] won't work because they all spawn back immediately 

---- Minecraft Crash Report ----


// I just don't know what went wrong :(

Time: 2/20/16 1:27 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:270)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:716)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:264)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 273290848 bytes (260 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 Optifine OptiFine_1.8_HD_U_H2 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	RadixCore{1.8-2.1.0} [RadixCore] (RadixCore-1.8-2.1.0-universal.jar) 
	UCHIJAAAA	MCA{1.8-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8-5.1.1.2-universal.jar) 

	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['santino12'/3867, l='world', x=235.42, y=62.00, z=213.17]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by WildBamaBoy** [comment]
Your first crash report is typical world corruption. Little I could do about that. The second one, turn off overwriting villagers in MCA's config and see if the problem still happens.

**Comment by WildBamaBoy** [comment]
Closing due to lack of response
