### ISSUE TITLE
Server crashes when telling child to create a farm [1.8.9]

### ISSUE THREAD

**Issue by kotoroshinoto** [WildBamaBoy/minecraft-comes-alive#646]
Child did not have the required plant/seeds in inventory, in case that is relevant

[10:25:49] [Server thread/INFO] [STDOUT]: [mcjty.lib.preferences.PreferencesProperties:syncToClient:38]: syncToClient: style = STYLE_FLAT_GRADIENT
[10:26:36] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@7c36a96d:
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at mca.api.CropEntry.getCropName(CropEntry.java:87) ~[CropEntry.class:?]
        at mca.ai.AIFarming.startFarming(AIFarming.java:341) ~[AIFarming.class:?]
        at mca.packets.PacketToggleAI.processOnGameThread(PacketToggleAI.java:117) ~[PacketToggleAI.class:?]
        at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:164) ~[AbstractPacketHandler.class:?]
        at mca.core.forge.EventHooksFML.serverTickEventHandler(EventHooksFML.java:175) ~[EventHooksFML.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_EventHooksFML_serverTickEventHandler_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:594) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
        ... 12 more
Caused by: java.lang.NullPointerException

**Comment by WildBamaBoy** [comment]
#624
