### ISSUE TITLE
Crash while loading 

### ISSUE THREAD

**Issue by zuoanqh** [WildBamaBoy/minecraft-comes-alive#681]
Using forge 1865, MCA 5.1.2, Radix Core 2.1.0

Crash when loading mods.
While the log does not suggest MCA by itself, when removing only the MCA, problem is fixed. 
Here's the log:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.1.jar)
  Reborn Core ASM (RebornCore-1.9-2.0.5.50-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 4/17/16 5:19 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.util.IntIdentityHashBiMap.func_186814_a(IntIdentityHashBiMap.java:98)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.addObjectRaw(FMLControlledNamespacedRegistry.java:546)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.set(FMLControlledNamespacedRegistry.java:165)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.loadRegistry(PersistentRegistryManager.java:308)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.freezeData(PersistentRegistryManager.java:391)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:746)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:307)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.util.IntIdentityHashBiMap.func_186814_a(IntIdentityHashBiMap.java:98)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.addObjectRaw(FMLControlledNamespacedRegistry.java:546)
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.set(FMLControlledNamespacedRegistry.java:165)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.loadRegistry(PersistentRegistryManager.java:308)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.freezeData(PersistentRegistryManager.java:391)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:746)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:307)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 752625136 bytes (717 MB) / 1896873984 bytes (1809 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJA	Baubles{1.2.0.1} [Baubles] (Baubles-1.9-1.2.0.1.jar) 
	UCHIJA	BaublesHud{2.3.0} [Baubles-Hud] (BaublesHud-1.9-2.3.0.jar) 
	UCHIJA	BetterAchievements{0.2.2} [Better Achievements] (BetterAchievements-1.9-0.2.2.jar) 
	UCHIJA	betterquesting{1.2.82} [Better Questing] (BetterQuesting-1.2.82.jar) 
	UCHIJA	bq_themed{0.0.2 Alpha} [ThemedQuestingPack] (bq_themed-1.2.0.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.13.jar) 
	UCHIJA	clayworldgen{1.1.0} [Clay WorldGen] (ClayWorldGen-1.1.0-1.9.jar) 
	UCHIJA	cookingforblockheads{2.0.5} [Cooking for Blockheads] (CookingForBlockheads-mc1.9-2.0.5.jar) 
	UCHIJA	craftelytra{1.0} [Craftable Elytra] (CraftableElytra-1.0.jar) 
	UCHIJA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJA	substratum{1.3.0.0} [Substratum] (Substratum-1.9-1.3.0.0.jar) 
	UCHIJA	foundry{2.0.0.0-alpha2} [Foundry] (Foundry-1.9-2.0.0.0-alpha2.jar) 
	UCHIJA	harvestchevsky{b4c} [Gentle Harvest] (Gentle_Harvest_1.9_b4c.jar) 
	UCHIJA	hgp{Release} [Horizontal Glass Panes] (hgp-1.9-1.0.2.jar) 
	UCHIJA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UCHIJA	JEI{3.2.10.185} [Just Enough Items] (jei_1.9-3.2.10.185.jar) 
	UCHIJA	journeymap{1.9-5.1.6b2} [JourneyMap] (journeymap-1.9-5.1.6b2-unlimited.jar) 
	UCHIJA	jeresources{0.4.3} [Just Enough Resources] (JustEnoughResources-1.9-0.4.3.jar) 
	UCHIJA	Login_Shield_MC1.9{1.2-21-g08fa29a} [Login Shield] (Login_Shield_MC1.9-1.2-21-g08fa29a.jar) 
	UCHIJA	LunatriusCore{1.1.2.34} [LunatriusCore] (LunatriusCore-1.9-1.1.2.34-universal.jar) 
	UCHIJA	malisiscore{1.9-3.0.1} [MalisisCore] (malisiscore-1.9-3.0.1.jar) 
	UCHIJA	malisisadvert{1.9-3.0.0} [Malisis Advert] (malisisadvert-1.9-3.0.0.jar) 
	UCHIJA	malisisdoors{1.9-4.0.0} [MalisisDoors] (malisisdoors-1.9-4.0.0.jar) 
	UCHIJA	mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar) 
	UCHIJA	RadixCore{1.9-2.1.0} [RadixCore] (RadixCore-1.9-2.1.0-BETA-universal.jar) 
	UCHIJA	MCA{1.9-5.1.2} [Minecraft Comes Alive] (MCA-1.9-5.1.2-BETA-universal.jar) 
	UCHIJA	mcmultipart{1.1.1} [MCMultiPart] (MCMultiPart-1.1.1-universal.jar) 
	UCHIJA	middletorch{3.0.3} [The Middle Torch] (middletorch-3.0.3.jar) 
	UCHIJA	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.jar) 
	UCHIJA	morematerials{1.0.20150301.0} [More Materials] (morematerials-1.9.20160320.0.jar) 
	UCHIJA	samsmountedpearl{1.0.1} [Mounted Pearl] (MountedPearl-1.9-1.0.1.jar) 
	UCHIJA	reborncore{2.0.5.50} [RebornCore] (RebornCore-1.9-2.0.5.50-universal.jar) 
	UCHIJA	redstonepaste{1.7.3} [Redstone Paste] (redstonepaste-mc1.9-1.7.3.jar) 
	UCHIJA	xreliquary{1.9-1.3.1.315} [Reliquary] (Reliquary-1.9-1.3.1.315.jar) 
	UCHIJA	rftools{4.30} [RFTools] (rftools-1.9.0-4.30.jar) 
	UCHIJA	RTG{1.9-0.0.5} [Realistic Terrain Generation] (RTG-1.9-0.0.5.jar) 
	UCHIJA	SaltMod{1.8.b} [Salty Mod] (SaltyMod-1.9-1.8.b_beta-2.jar) 
	UCHIJA	Schematica{1.7.7.145} [Schematica] (Schematica-1.9-1.7.7.145-universal.jar) 
	UCHIJA	sciapi{1.3.0.3} [SciAPI] (SciAPI-1.3.0.3.jar) 
	UCHIJA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.jar) 
	UCHIJA	bq_standard{1.2.58} [Standard Expansion] (StandardExpansion-1.2.58.jar) 
	UCHIJA	stellarsky{0.3.2.5b} [Stellar Sky] (Stellar Sky-0.3.2.5b.jar) 
	UCHIJA	techreborn{1.0.5.173} [TechReborn] (TechReborn-1.9-1.0.5.173-universal.jar) 
	UCHIJA	terrariabuttons{1.0.1} [Terraria Buttons] (TerrariaButtons-1.9-1.0.1.jar) 
	UCHIJA	VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJA	VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJA	vending{1.3.1} [vending] (vending-1.9-1.3.4.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	UCHIJA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UCHIJA	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9-2.2.0.186.jar) 
	UCHIJA	wawla{2.2.0.178} [What Are We Looking At] (Wawla-1.9-2.2.0.186.jar) 
	UCHIJA	weaponcaseloot{3.0.0-alpha} [WeaponCaseLoot] (weaponcaseloot-3.0.0-alpha.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  net.fybertech.nwr.NowWithRendering
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
Reborn Core ASM (RebornCore-1.9-2.0.5.50-universal.jar)
  reborncore.asm.RebornClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 354.35' Renderer: 'GeForce GT 755M/PCIe/SSE2'
	Launched Version: forge-12.16.0.1865
	LWJGL: 2.9.4
	OpenGL: GeForce GT 755M/PCIe/SSE2 GL version 4.5.0 NVIDIA 354.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
```

**Comment by WildBamaBoy** [comment]
Remove all mods except MCA, then try again and provide a new crash report.

**Comment by zuoanqh** [comment]
Hi, after a lot of binary searching, guessing and agony, I found it requires minimally 6 mods to trigger this crash, their names are:

![image](https://cloud.githubusercontent.com/assets/8357370/14586241/dacffdd0-04cc-11e6-992a-cde755e3f2d9.png)

Removing either Foundry or MalisisDoors cause this crash to go away. (Substratum is the "core" required by Foundry)

Additionally, with the initial mod pack (as in the crash report), if i only remove LunatriusCore and Schematica, there is no crash, as if something in between fixed it, only to be broken again by these two -- There is no crash when these two are added to the 6 mods without either Foundry or Malisisdoor. I have also read through the mods list in game with full modpack except Schematica, all the 6 crush-inducing mods are indeed loaded.

Do you want me to find out which mod(s) might have "fixed" it, or the above information can give you some good guesses already?

**Comment by WildBamaBoy** [comment]
It's probably MalisisCore - I see in the crash report it is a core mod, meaning it makes changes that are prone to crashes when not using the right Forge version, especially on the 1.9 branch as it doesn't yet have a recommended release.

Double-check to see if MalisisCore requires a specific 1.9 Forge version and make sure you're using that.

Otherwise this doesn't appear to be an issue with MCA itself (it performs no core modifications), so I'll go ahead and close this.
