### ISSUE TITLE
Game keeps crashing, won't let me interact with villagers?!? 

### ISSUE THREAD

**Issue by SilentWolf101** [WildBamaBoy/minecraft-comes-alive#705]
- [Yes for 1.8] I am running the latest mod versions of MCA and RadixCore.
- [Yes] I can reproduce this issue with just MCA and RadixCore installed.
- [Yes] I can provide my Minecraft version and MCA version.
- [Yes, but not very far] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [Yes] I am crashing and can provide my crash report.

## Versions
Minecraft: 1.8 (Just 1.8, not 1.8.whatever) 
MCA: 1.8-5.0.7.1 (tried all the versions) 
RadixCore: 1.8-2.0.5 (Again, trying all versions) 

## Issue Description
The game just crashes upon right clicking a villager, then says "This villager is being interacted with" when reopening minecraft and right clicking. It's not my computer's fault, because my computer can almost be considered a gaming computer. Almost.

## Reproduce Steps
So, I was playing my game yesterday, married a villager, changed her settings with the creative mode book, and then put her in a house I made. I interacted with her -- chat, joke, gift, everything worked. I had all my 60 something of my mods installed, no problems. 

Today, I logged on, went to build for a bit, then went to my wife. I right clicked on her, my game froze, then crashed. I reopened my game, tried right clicking on her, and it kept saying "This villager is being interacted with." So, I tried interacting with another villager, and again, game crashed. Won't even open up the menu of things to do. 

Opened a new flat creative world, tried spawning in a girl. My game couldn't load her and crashed. Took all my mods out, left in MCA and RadixCore, opened up a NEW world, spawned in a girl, tried interacting with her, and my game still crashed. Tried deleting and redownloading the version I have, same thing. Tried deleting and downloading different versions of MCA and RadixCore, same thing. Googled way to fix this, couldn't find a solution. So I came here for help. 

## Additional Information
Latest crash report with above settings. 

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 5/16/16 7:01 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mca.core.MCA.getPlayerData(MCA.java:651)
	at mca.client.gui.GuiInteraction.<init>(GuiInteraction.java:91)
	at mca.packets.PacketOpenGUIOnEntity.processOnGameThread(PacketOpenGUIOnEntity.java:66)
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:164)
	at mca.core.forge.EventHooksFML.clientTickEventHandler(EventHooksFML.java:117)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_EventHooksFML_clientTickEventHandler_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:371)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2152)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at mca.core.MCA.getPlayerData(MCA.java:651)
	at mca.client.gui.GuiInteraction.<init>(GuiInteraction.java:91)
	at mca.packets.PacketOpenGUIOnEntity.processOnGameThread(PacketOpenGUIOnEntity.java:66)
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:164)
	at mca.core.forge.EventHooksFML.clientTickEventHandler(EventHooksFML.java:117)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_EventHooksFML_clientTickEventHandler_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:371)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['spittank'/4, l='MpServer', x=-9.36, y=237.00, z=-11.24]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,4.00,0.00 - World: (0,4,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1204 game time, 1204 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityHuman['Eden'/0, l='MpServer', x=-15.66, y=237.02, z=-28.34], EntityHuman['Becky'/1, l='MpServer', x=-1.72, y=237.02, z=-29.25], EntityHuman['Elise'/2, l='MpServer', x=-10.31, y=237.02, z=-11.97], EntityHuman['Celeste'/3, l='MpServer', x=-10.06, y=237.02, z=-10.19], EntityPlayerSP['spittank'/4, l='MpServer', x=-9.36, y=237.00, z=-11.24]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 379960256 bytes (362 MB) / 735879168 bytes (701 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1565 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1565.jar) 
	UCHIJAAAA	Forge{11.14.4.1565} [Minecraft Forge] (forge-1.8-11.14.4.1565.jar) 
	UCHIJAAAA	RadixCore{1.8-2.0.5} [RadixCore] (RadixCore-1.8-2.0.5-universal.jar) 
	UCHIJAAAA	MCA{1.8-5.0.7.1} [Minecraft Comes Alive] (MCA-1.8-5.0.7.1-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.8-forge1.8-11.14.4.1565
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.4229, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [MCunleashed Default Resource Pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by SilentWolf101** [comment]
Alright, so I'm currently rebooting my entire minecraft, going to see if that helps anything... Will update when finished!

**Comment by SilentWolf101** [comment]
UPDATE: The complete reboot worked to where I was able to interact with the villagers again. However, while reinstalling my mods (one by one), I found that the problem occurred again when installing the Highlands mod, which I do love. But, I'd be willing to live without it if it means that I can play MCA. 

Still testing my other mods, though...

**Comment by SilentWolf101** [comment]
It's odd that every time I come across a problem mod, I have to completely reboot minecraft. As in delete everything in the minecraft folder, then slowly add the mods back in... :\

**Comment by WildBamaBoy** [comment]
1.8 is no longer supported unfortunately. Update to 1.8.9 or 1.9.
