### ISSUE TITLE
Crash when loading a save where a villager is fishing

### ISSUE THREAD

**Issue by Victiny** [WildBamaBoy/minecraft-comes-alive#762]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can provide my Minecraft version and MCA version.
- [x] I am crashing and can provide my crash report.

## Versions
Minecraft 1.8.9 : MCA 5.2.0

## Reproduce Steps
in loading

## Additional Information
A part of crash log:

Description: Ticking entity
java.lang.NullPointerException: Ticking entity
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java:206)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:251)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java:206)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityChoreFishHook (mca.entity.EntityChoreFishHook)
	Entity ID: 175
	Entity Name: entity.MCA.EntityChoreFishHook.name
	Entity's Exact location: 335.22, 62.90, -292.25
	Entity's Block location: 335.00,62.00,-293.00 - World: (335,62,-293), Chunk: (at 15,3,11 in 20,-19; contains blocks 320,0,-304 to 335,255,-289), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.00, -0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

**Comment by WildBamaBoy** [comment]
1.8.9 is no longer supported.
