### ISSUE TITLE
Cannot attack/click on villager

### ISSUE THREAD

**Issue by sethleedy** [WildBamaBoy/minecraft-comes-alive#764]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

## Versions
1.7.10
MCA-1.7.10-5.2.1-universal.jar

## Issue Description
Went to attack a zombie with a mod glass sword.

## Additional Information
java.lang.ClassCastException: net.minecraft.entity.passive.EntityVillager cannot be cast to mca.entity.EntityHuman
	at mca.core.forge.EventHooksForge.onLivingAttack(EventHooksForge.java:259)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_36_EventHooksForge_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:292)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:737)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54)
	at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:222)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:406)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1393)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by sethleedy** [comment]
Same as listed before. Hoping my crash report helps.

**Comment by shadowbolt79** [comment]
Same as #754
