### ISSUE TITLE
game crash while attacking vanilla villagers

### ISSUE THREAD

**Issue by HENREX** [WildBamaBoy/minecraft-comes-alive#770]
#

- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

1.10.2 5.2.1

game crash while attacking vanilla villagers

1.set Overwrite original villagers to false
2.attack a vanilla villager
3.the game will crash 

---- Minecraft Crash Report ----
// Oops.

Time: 2016/8/15 上午 3:57
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.entity.passive.EntityVillager cannot be cast to mca.entity.EntityHuman
	at mca.core.forge.EventHooksForge.onLivingAttack(EventHooksForge.java:277)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_EventHooksForge_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:496)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:820)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:526)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452)
	at net.minecraft.client.Minecraft.redirect$onClickMouse$0(Minecraft.java:118)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mca.core.forge.EventHooksForge.onLivingAttack(EventHooksForge.java:277)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_EventHooksForge_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:496)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:820)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:526)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452)
	at net.minecraft.client.Minecraft.redirect$onClickMouse$0(Minecraft.java:118)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['HENREX'/140, l='MpServer', x=141.30, y=6.53, z=208.70]]
	Chunk stats: MultiplayerChunkCache: 434, 434
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (53,4,39), Chunk: (at 5,0,7 in 3,2; contains blocks 48,0,32 to 63,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 69130 game time, 69130 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 72 total; [EntityPlayerSP['HENREX'/140, l='MpServer', x=141.30, y=6.53, z=208.70], EntityVillager['Villager'/136, l='MpServer', x=153.59, y=4.00, z=238.24], EntityVillager['Villager'/137, l='MpServer', x=160.07, y=5.00, z=227.49], EntitySpider['Spider'/138, l='MpServer', x=182.03, y=4.00, z=241.01], EntitySpider['Spider'/139, l='MpServer', x=190.91, y=4.00, z=250.57], EntityCreeper['Creeper'/141, l='MpServer', x=174.50, y=4.00, z=274.50], EntitySkeleton['Skeleton'/20237, l='MpServer', x=103.50, y=4.00, z=134.50], EntitySpider['Spider'/143, l='MpServer', x=150.50, y=4.00, z=282.50], EntityZombie['Zombie'/144, l='MpServer', x=142.61, y=4.00, z=271.11], EntityCreeper['Creeper'/145, l='MpServer', x=190.83, y=4.00, z=262.18], EntitySkeleton['Skeleton'/20244, l='MpServer', x=207.50, y=4.00, z=283.50], EntitySkeleton['Skeleton'/38, l='MpServer', x=127.50, y=4.00, z=143.50], EntityVillager['Villager'/40, l='MpServer', x=142.70, y=5.00, z=173.50], EntityVillager['Villager'/41, l='MpServer', x=140.42, y=5.00, z=173.50], EntityZombie['Zombie'/42, l='MpServer', x=137.79, y=5.00, z=175.30], EntityZombie['Zombie'/43, l='MpServer', x=137.20, y=5.00, z=175.30], EntitySkeleton['Skeleton'/44, l='MpServer', x=139.25, y=4.00, z=191.70], EntityVillager['Villager'/45, l='MpServer', x=156.25, y=4.00, z=218.55], EntityZombie['Zombie'/4909, l='MpServer', x=131.50, y=5.00, z=213.70], EntityZombie['Zombie'/46, l='MpServer', x=155.23, y=3.94, z=213.55], EntityVillager['Villager'/47, l='MpServer', x=136.70, y=5.00, z=215.50], EntitySpider['Spider'/50, l='MpServer', x=152.50, y=4.00, z=135.50], EntityEnderman['Enderman'/51, l='MpServer', x=150.50, y=4.00, z=133.50], EntitySpider['Spider'/52, l='MpServer', x=151.85, y=4.00, z=163.60], EntityVillager['Villager'/53, l='MpServer', x=156.50, y=4.00, z=181.75], EntitySpider['Spider'/4917, l='MpServer', x=70.07, y=4.00, z=176.08], EntityZombie['entity.Zombie.name'/26165, l='MpServer', x=172.56, y=5.00, z=215.48], EntityVillager['Villager'/54, l='MpServer', x=155.33, y=4.00, z=216.70], EntityVillager['Villager'/55, l='MpServer', x=147.49, y=5.00, z=215.39], EntityVillager['Villager'/56, l='MpServer', x=141.51, y=5.00, z=208.07], EntityVillager['Villager'/57, l='MpServer', x=159.43, y=5.00, z=217.50], EntityVillager['Villager'/58, l='MpServer', x=155.72, y=4.00, z=217.68], EntityVillager['Villager'/59, l='MpServer', x=153.30, y=5.00, z=228.30], EntitySpider['Spider'/4923, l='MpServer', x=154.50, y=4.00, z=159.50], EntityVillager['Villager'/60, l='MpServer', x=154.08, y=5.00, z=229.09], EntitySkeleton['Skeleton'/4925, l='MpServer', x=93.50, y=4.00, z=238.50], EntitySpider['Spider'/62, l='MpServer', x=167.79, y=4.00, z=158.65], EntityZombie['Zombie'/63, l='MpServer', x=164.22, y=4.00, z=172.42], EntitySkeleton['Skeleton'/64, l='MpServer', x=166.63, y=9.50, z=199.23], EntityCreeper['Creeper'/65, l='MpServer', x=181.48, y=4.00, z=205.83], EntityVillager['Villager'/66, l='MpServer', x=160.52, y=5.00, z=191.26], EntityVillager['Villager'/68, l='MpServer', x=167.56, y=5.00, z=221.30], EntityZombie['Zombie'/69, l='MpServer', x=173.31, y=5.00, z=216.09], EntityVillager['Villager'/70, l='MpServer', x=172.01, y=5.00, z=231.09], EntitySpider['Spider'/71, l='MpServer', x=169.26, y=4.00, z=228.98], EntityCreeper['Creeper'/75, l='MpServer', x=188.50, y=4.00, z=142.50], EntitySpider['Spider'/76, l='MpServer', x=181.50, y=4.00, z=137.50], EntityCreeper['Creeper'/77, l='MpServer', x=177.50, y=4.00, z=156.50], EntitySkeleton['Skeleton'/78, l='MpServer', x=186.70, y=4.00, z=154.48], EntitySkeleton['Skeleton'/79, l='MpServer', x=186.79, y=4.00, z=148.19], EntitySpider['Spider'/80, l='MpServer', x=179.97, y=4.00, z=160.07], EntityVillager['Villager'/81, l='MpServer', x=155.81, y=4.94, z=169.50], EntitySkeleton['Skeleton'/82, l='MpServer', x=177.72, y=4.00, z=184.55], EntityVillager['Villager'/83, l='MpServer', x=172.43, y=4.00, z=203.48], EntitySpider['Spider'/84, l='MpServer', x=184.11, y=4.00, z=201.40], EntityVillager['Villager'/85, l='MpServer', x=172.67, y=5.00, z=209.50], EntityVillager['Villager'/86, l='MpServer', x=181.70, y=5.79, z=215.30], EntityVillager['Villager'/87, l='MpServer', x=187.62, y=5.00, z=208.67], EntityZombie['Zombie'/88, l='MpServer', x=181.09, y=5.00, z=215.52], EntityVillager['Villager'/89, l='MpServer', x=185.53, y=3.94, z=211.84], EntityVillager['Villager'/90, l='MpServer', x=187.02, y=5.00, z=207.90], EntityCreeper['Creeper'/91, l='MpServer', x=191.20, y=4.94, z=219.71], EntitySpider['Spider'/93, l='MpServer', x=205.50, y=4.00, z=184.50], EntitySkeleton['Skeleton'/94, l='MpServer', x=203.79, y=4.00, z=218.79], EntityCreeper['Creeper'/95, l='MpServer', x=204.50, y=4.00, z=210.50], EntityVillager['Villager'/96, l='MpServer', x=197.53, y=5.00, z=225.72], EntityVillager['Villager'/97, l='MpServer', x=198.88, y=5.00, z=226.58], EntityWitch['Witch'/103, l='MpServer', x=216.50, y=4.00, z=137.50], EntitySpider['Spider'/105, l='MpServer', x=211.01, y=4.00, z=166.01], EntitySkeleton['Skeleton'/106, l='MpServer', x=221.32, y=4.00, z=193.73], EntitySkeleton['Skeleton'/108, l='MpServer', x=215.28, y=4.00, z=223.45], EntityCreeper['Creeper'/20215, l='MpServer', x=221.50, y=4.00, z=248.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 293078568 bytes (279 MB) / 667205632 bytes (636 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2011 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2011.jar) 
	UCHIJAAAA	Forge{12.18.1.2011} [Minecraft Forge] (forge-1.10.2-12.18.1.2011.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.1} [Minecraft Comes Alive] (MCA-1.10.2-5.2.1-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5700 Series'
	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5700 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: CMM.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz

**Comment by HENREX** [comment]
it should be the same issue as #754
