### ISSUE TITLE
player-with-player baby crash still not fixed

### ISSUE THREAD

**Issue by JohnRohner** [WildBamaBoy/minecraft-comes-alive#775]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

**Comment by JohnRohner** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/19/16 2:07 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at mca.items.ItemBaby.updateBabyGrowth(ItemBaby.java:205)
    at mca.items.ItemBaby.onEntityItemUpdate(ItemBaby.java:166)
    at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:91)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1750)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at mca.items.ItemBaby.updateBabyGrowth(ItemBaby.java:205)
    at mca.items.ItemBaby.onEntityItemUpdate(ItemBaby.java:166)
    at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:91)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
    Entity Type: Item (net.minecraft.entity.item.EntityItem)
    Entity ID: 192
    Entity Name: item.item.BabyGirl
    Entity's Exact location: -37.95, 187.00, -14.88
    Entity's Block location: World: (-38,187,-15), Chunk: (at 10,11,1 in -3,-1; contains blocks -48,0,-16 to -33,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1750)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['a'/374, l='MpServer', x=-28.01, y=187.00, z=-15.54]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 37145992 game time, 13417704 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 179 total; [EntityChicken['Chicken'/256, l='MpServer', x=-11.52, y=112.00, z=36.63], EntityPlayerSP['a'/374, l='MpServer', x=-28.01, y=187.00, z=-15.54], EntityItem['item.item.egg'/257, l='MpServer', x=-11.16, y=112.00, z=36.13], EntityCow['Cow'/268, l='MpServer', x=9.81, y=77.00, z=-94.54], EntitySkeleton['Skeleton'/269, l='MpServer', x=8.50, y=135.00, z=-71.50], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/270, l='MpServer', x=13.67, y=149.00, z=-74.76], EntityChicken['Chicken'/271, l='MpServer', x=13.98, y=145.00, z=-76.32], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/272, l='MpServer', x=0.45, y=166.00, z=-74.50], EntitySheep['Sheep'/273, l='MpServer', x=12.17, y=161.00, z=-70.51], EntityZombie['Zombie'/274, l='MpServer', x=7.35, y=130.00, z=-54.65], EntityZombie['entity.Zombie.name'/275, l='MpServer', x=9.50, y=131.00, z=-59.50], EntityConcussionCreeper['Concussion Creeper'/276, l='MpServer', x=11.50, y=129.00, z=-62.50], EntityChicken['Chicken'/277, l='MpServer', x=3.22, y=186.00, z=-62.96], EntityItem['item.item.egg'/278, l='MpServer', x=3.76, y=186.00, z=-63.52], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/279, l='MpServer', x=10.59, y=158.00, z=-37.85], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/280, l='MpServer', x=14.80, y=173.00, z=-47.37], EntityConcussionCreeper['Concussion Creeper'/281, l='MpServer', x=12.84, y=175.00, z=-47.50], EntityChicken['Chicken'/282, l='MpServer', x=6.33, y=176.00, z=-40.03], EntityItem['item.item.egg'/283, l='MpServer', x=6.22, y=176.00, z=-40.27], EntitySkeleton['Skeleton'/3355, l='MpServer', x=3.50, y=72.00, z=-37.50], EntitySheep['Sheep'/284, l='MpServer', x=4.52, y=76.00, z=-19.82], EntityChicken['Chicken'/285, l='MpServer', x=4.53, y=68.45, z=-30.20], EntityItem['item.item.egg'/286, l='MpServer', x=5.20, y=76.00, z=-22.58], EntityChicken['Chicken'/287, l='MpServer', x=14.39, y=69.00, z=-22.10], EntityItem['item.item.egg'/288, l='MpServer', x=14.57, y=69.00, z=-22.88], EntityChicken['Chicken'/289, l='MpServer', x=5.57, y=177.00, z=-23.49], EntitySheep['Sheep'/290, l='MpServer', x=7.52, y=77.00, z=-3.82], EntityItem['item.item.egg'/291, l='MpServer', x=0.06, y=118.00, z=-2.13], EntityChicken['Chicken'/292, l='MpServer', x=4.94, y=133.00, z=5.40], EntityItem['item.item.egg'/293, l='MpServer', x=4.13, y=133.00, z=5.72], EntitySkeleton['Skeleton'/294, l='MpServer', x=12.50, y=83.00, z=27.50], EntityPig['Pig'/308, l='MpServer', x=28.42, y=61.39, z=-91.55], EntitySheep['Sheep'/309, l='MpServer', x=26.58, y=61.20, z=-89.49], EntityChicken['Chicken'/310, l='MpServer', x=20.49, y=101.00, z=-77.90], EntityChicken['Chicken'/311, l='MpServer', x=21.50, y=148.00, z=-64.20], EntityItem['item.item.egg'/312, l='MpServer', x=21.13, y=148.00, z=-64.70], EntityChicken['Chicken'/313, l='MpServer', x=28.59, y=145.00, z=-60.70], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/314, l='MpServer', x=27.53, y=145.00, z=-51.21], EntitySheep['Sheep'/315, l='MpServer', x=24.83, y=160.00, z=-60.45], EntitySheep['Sheep'/316, l='MpServer', x=21.54, y=76.00, z=-30.19], EntitySkeleton['Skeleton'/2365, l='MpServer', x=-74.50, y=105.00, z=-19.50], EntityPig['Pig'/325, l='MpServer', x=46.67, y=72.00, z=-92.50], EntityCow['Cow'/336, l='MpServer', x=49.57, y=65.00, z=-89.78], EntityPig['Pig'/86, l='MpServer', x=-105.55, y=60.00, z=-77.55], EntityChicken['Chicken'/87, l='MpServer', x=-105.96, y=70.00, z=-52.54], EntitySheep['Sheep'/92, l='MpServer', x=-106.20, y=68.00, z=43.63], EntitySheep['Sheep'/95, l='MpServer', x=-105.51, y=67.00, z=62.21], EntityCow['Cow'/100, l='MpServer', x=-84.23, y=64.00, z=-85.43], EntityItem['item.item.bone'/101, l='MpServer', x=-84.97, y=100.00, z=-78.84], EntitySpider['Spider'/102, l='MpServer', x=-83.50, y=188.00, z=-76.50], EntityConcussionCreeper['Concussion Creeper'/103, l='MpServer', x=-80.50, y=76.00, z=-35.50], EntitySheep['Sheep'/104, l='MpServer', x=-95.16, y=120.00, z=-32.53], EntityCreeper['Creeper'/105, l='MpServer', x=-91.50, y=77.00, z=-22.50], EntityChicken['Chicken'/106, l='MpServer', x=-92.81, y=99.00, z=-18.00], EntityCreeper['Creeper'/107, l='MpServer', x=-80.50, y=96.00, z=-19.50], EntitySkeleton['Skeleton'/108, l='MpServer', x=-81.50, y=96.00, z=-20.50], EntitySkeleton['Skeleton'/109, l='MpServer', x=-87.25, y=97.00, z=-13.73], EntityCreeper['Creeper'/110, l='MpServer', x=-83.50, y=96.00, z=-22.50], EntitySkeleton['Skeleton'/111, l='MpServer', x=-78.30, y=96.00, z=-15.43], EntitySheep['Sheep'/114, l='MpServer', x=-85.60, y=145.00, z=-23.24], EntityConcussionCreeper['Concussion Creeper'/115, l='MpServer', x=-83.89, y=95.00, z=-13.88], EntityZombie['Zombie'/116, l='MpServer', x=-76.77, y=97.00, z=-16.50], EntityConcussionCreeper['Concussion Creeper'/117, l='MpServer', x=-80.50, y=82.00, z=-8.50], EntityItem['item.item.egg'/373, l='MpServer', x=28.13, y=99.00, z=-62.02], EntitySkeleton['Skeleton'/118, l='MpServer', x=-86.48, y=98.00, z=-16.29], EntitySkeleton['Skeleton'/119, l='MpServer', x=-90.49, y=80.00, z=-6.25], EntityCreeper['Creeper'/120, l='MpServer', x=-84.00, y=94.00, z=-11.50], EntityCreeper['Creeper'/121, l='MpServer', x=-84.70, y=94.00, z=-13.35], EntitySkeleton['Skeleton'/122, l='MpServer', x=-87.70, y=97.00, z=-14.59], EntitySkeleton['Skeleton'/123, l='MpServer', x=-82.32, y=95.00, z=-14.09], EntitySheep['Sheep'/124, l='MpServer', x=-93.45, y=53.00, z=47.55], EntitySheep['Sheep'/125, l='MpServer', x=-83.52, y=69.00, z=46.20], EntityPig['Pig'/126, l='MpServer', x=-95.30, y=70.00, z=60.43], EntityCreeper['Creeper'/1925, l='MpServer', x=-71.50, y=106.00, z=-36.50], EntitySheep['Sheep'/134, l='MpServer', x=-71.36, y=62.07, z=-82.45], EntityZombie['Zombie'/135, l='MpServer', x=-69.50, y=152.00, z=-56.50], EntitySheep['Sheep'/136, l='MpServer', x=-70.55, y=161.00, z=-61.45], EntitySkeleton['Skeleton'/137, l='MpServer', x=-74.50, y=75.00, z=-43.50], EntityZombie['Zombie'/138, l='MpServer', x=-73.50, y=110.00, z=-33.50], EntityCreeper['Creeper'/139, l='MpServer', x=-66.50, y=102.00, z=-46.50], EntityCreeper['Creeper'/140, l='MpServer', x=-64.50, y=166.00, z=-40.50], EntitySkeleton['Skeleton'/141, l='MpServer', x=-64.50, y=166.00, z=-40.50], EntityCreeper['Creeper'/142, l='MpServer', x=-74.57, y=182.00, z=-46.85], EntitySkeleton['Skeleton'/143, l='MpServer', x=-76.46, y=177.00, z=-45.91], EntitySkeleton['Skeleton'/144, l='MpServer', x=-67.50, y=69.00, z=-26.50], EntityConcussionCreeper['Concussion Creeper'/145, l='MpServer', x=-69.50, y=81.00, z=-27.50], EntityCreeper['Creeper'/146, l='MpServer', x=-70.50, y=84.00, z=-25.50], EntityZombie['Zombie'/147, l='MpServer', x=-73.50, y=90.00, z=-19.76], EntityConcussionCreeper['Concussion Creeper'/148, l='MpServer', x=-79.50, y=95.00, z=-31.50], EntityConcussionCreeper['Concussion Creeper'/149, l='MpServer', x=-74.81, y=95.00, z=-28.50], EntitySkeleton['Skeleton'/150, l='MpServer', x=-76.50, y=95.00, z=-30.50], EntityZombie['Zombie'/151, l='MpServer', x=-78.50, y=96.00, z=-17.50], EntityChicken['Chicken'/152, l='MpServer', x=-75.31, y=185.00, z=-27.06], EntityItem['item.item.egg'/153, l='MpServer', x=-75.15, y=185.00, z=-26.37], EntitySheep['Sheep'/158, l='MpServer', x=-50.82, y=121.00, z=-93.54], EntityZombie['Zombie'/159, l='MpServer', x=-63.50, y=161.00, z=-40.50], EntityChicken['Chicken'/160, l='MpServer', x=-61.02, y=185.00, z=-45.50], EntityItem['item.item.egg'/161, l='MpServer', x=-61.09, y=185.00, z=-45.58], EntitySquid['Squid'/163, l='MpServer', x=-52.60, y=61.85, z=-25.24], EntitySkeleton['Skeleton'/164, l='MpServer', x=-56.50, y=81.00, z=-21.50], EntityConcussionCreeper['Concussion Creeper'/165, l='MpServer', x=-49.50, y=83.00, z=-31.50], EntityItem['item.item.egg'/166, l='MpServer', x=-56.54, y=85.00, z=10.75], EntityChicken['Chicken'/167, l='MpServer', x=-54.82, y=98.00, z=9.44], EntitySkeleton['Skeleton'/168, l='MpServer', x=-48.50, y=147.00, z=9.50], EntityChicken['Chicken'/169, l='MpServer', x=-57.22, y=62.63, z=24.49], EntityCow['Cow'/176, l='MpServer', x=-47.73, y=118.00, z=-88.16], EntitySheep['Sheep'/177, l='MpServer', x=-44.97, y=113.00, z=-86.55], EntitySheep['Sheep'/178, l='MpServer', x=-40.73, y=62.10, z=-76.27], EntityChicken['Chicken'/179, l='MpServer', x=-39.18, y=154.00, z=-63.50], EntityChicken['Chicken'/180, l='MpServer', x=-35.96, y=168.00, z=-62.51], EntitySkeleton['Skeleton'/182, l='MpServer', x=-35.58, y=81.00, z=-42.81], EntityConcussionCreeper['Concussion Creeper'/183, l='MpServer', x=-42.50, y=120.00, z=-35.50], EntityWitch['Witch'/184, l='MpServer', x=-37.50, y=141.00, z=-38.50], EntitySkeleton['Skeleton'/185, l='MpServer', x=-34.50, y=141.00, z=-41.50], EntitySkeleton['Skeleton'/186, l='MpServer', x=-31.73, y=142.00, z=-39.52], EntitySkeleton['Skeleton'/187, l='MpServer', x=-40.50, y=141.00, z=-34.50], EntitySkeleton['Skeleton'/188, l='MpServer', x=-40.50, y=141.00, z=-34.50], EntityCreeper['Creeper'/189, l='MpServer', x=-33.50, y=143.00, z=-38.50], EntitySkeleton['Skeleton'/190, l='MpServer', x=-43.50, y=71.00, z=-23.50], EntityArmorStand['Armor Stand'/191, l='MpServer', x=-39.50, y=177.00, z=-11.50], EntityItem['item.item.BabyGirl'/192, l='MpServer', x=-37.95, y=187.00, z=-14.88], EntityZombie['Zombie'/193, l='MpServer', x=-43.50, y=147.00, z=14.50], EntityCreeper['Creeper'/194, l='MpServer', x=-41.50, y=187.00, z=7.50], EntityZombie['Zombie'/195, l='MpServer', x=-45.50, y=77.00, z=18.50], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/196, l='MpServer', x=-37.47, y=138.00, z=30.54], EntityCreeper['Creeper'/197, l='MpServer', x=-38.50, y=140.00, z=17.50], EntityCreeper['Creeper'/453, l='MpServer', x=-62.50, y=72.00, z=-23.50], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/198, l='MpServer', x=-37.45, y=153.00, z=30.45], EntityChicken['Chicken'/199, l='MpServer', x=-35.28, y=153.00, z=31.90], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/200, l='MpServer', x=-44.75, y=152.00, z=28.54], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/201, l='MpServer', x=-34.47, y=155.00, z=31.85], EntitySkeleton['Skeleton'/202, l='MpServer', x=-32.50, y=74.00, z=37.50], EntityZombie['Zombie'/203, l='MpServer', x=-43.46, y=119.00, z=32.23], EntityItem['item.item.egg'/206, l='MpServer', x=-37.22, y=137.00, z=32.95], EntitySheep['Sheep'/209, l='MpServer', x=-16.47, y=125.00, z=-79.78], EntitySheep['Sheep'/210, l='MpServer', x=-21.47, y=154.00, z=-66.78], EntityChicken['Chicken'/211, l='MpServer', x=-21.31, y=159.00, z=-65.98], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/212, l='MpServer', x=-16.61, y=162.00, z=-70.85], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/213, l='MpServer', x=-20.62, y=163.00, z=-65.77], EntityItem['item.item.bone'/214, l='MpServer', x=-17.18, y=164.00, z=-68.19], EntityChicken['Chicken'/215, l='MpServer', x=-20.38, y=178.00, z=-64.99], EntityItem['item.item.egg'/216, l='MpServer', x=-19.85, y=177.00, z=-66.10], EntityChicken['Chicken'/217, l='MpServer', x=-27.96, y=159.00, z=-62.50], EntitySquid['Squid'/2009, l='MpServer', x=-51.50, y=62.00, z=-20.50], EntityItem['item.item.egg'/218, l='MpServer', x=-28.80, y=159.00, z=-62.16], EntityItem['item.item.egg'/219, l='MpServer', x=-24.52, y=161.00, z=-63.28], EntitySheep['Sheep'/220, l='MpServer', x=-24.97, y=178.00, z=-62.90], EntityChicken['Chicken'/221, l='MpServer', x=-21.20, y=181.00, z=-63.50], EntityChicken['Chicken'/222, l='MpServer', x=-24.20, y=178.00, z=-62.20], EntitySheep['Sheep'/223, l='MpServer', x=-11.77, y=187.00, z=-67.48], EntityCow['Cow'/224, l='MpServer', x=-17.48, y=189.00, z=-52.82], EntityItem['item.item.egg'/225, l='MpServer', x=-22.10, y=181.00, z=-63.30], EntitySkeleton['Skeleton'/226, l='MpServer', x=-16.50, y=82.00, z=-35.50], EntityChicken['Chicken'/227, l='MpServer', x=-25.51, y=188.50, z=-41.03], EntitySkeleton['Skeleton'/228, l='MpServer', x=-16.50, y=85.00, z=-27.50], EntityWitch['Witch'/229, l='MpServer', x=-16.50, y=84.00, z=-30.50], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/230, l='MpServer', x=-21.38, y=128.00, z=36.84], EntitySheep['Sheep'/234, l='MpServer', x=-0.57, y=139.00, z=-84.50], EntitySheep['Sheep'/235, l='MpServer', x=-10.17, y=129.00, z=-84.49], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/236, l='MpServer', x=-2.19, y=154.00, z=-78.50], EntitySheep['Sheep'/237, l='MpServer', x=-15.48, y=179.00, z=-69.82], EntityCow['Cow'/238, l='MpServer', x=-4.52, y=188.00, z=-64.80], EntitySheep['Sheep'/239, l='MpServer', x=-8.07, y=189.00, z=-57.31], EntityCow['Cow'/240, l='MpServer', x=-12.84, y=189.00, z=-53.47], EntitySheep['Sheep'/241, l='MpServer', x=-8.90, y=189.00, z=-55.70], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/242, l='MpServer', x=-10.07, y=189.00, z=-53.07], EntityConcussionCreeper['Concussion Creeper'/243, l='MpServer', x=-5.50, y=70.00, z=-25.50], EntitySkeleton['Skeleton'/244, l='MpServer', x=-14.51, y=67.00, z=-24.13], EntityConcussionCreeper['Concussion Creeper'/245, l='MpServer', x=-13.50, y=85.00, z=-23.50], EntitySkeleton['Skeleton'/246, l='MpServer', x=-9.50, y=100.00, z=-30.50], EntityConcussionCreeper['Concussion Creeper'/247, l='MpServer', x=-14.50, y=105.00, z=-25.50], EntityWitch['Witch'/248, l='MpServer', x=-14.50, y=121.00, z=-20.50], EntitySkeleton['Skeleton'/249, l='MpServer', x=-0.50, y=188.00, z=-22.68], EntityChicken['Chicken'/250, l='MpServer', x=-2.51, y=138.00, z=-2.87], EntityZombie['Zombie'/251, l='MpServer', x=-7.47, y=147.00, z=-2.76], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/252, l='MpServer', x=-3.47, y=162.00, z=-0.84], EntitySheep['§cM§6r. §eR§aa§2i§bn§3b§5o§dw'/253, l='MpServer', x=-3.49, y=171.00, z=9.73], EntitySheep['Sheep'/254, l='MpServer', x=-10.53, y=124.00, z=20.78], EntitySheep['Sheep'/255, l='MpServer', x=-7.53, y=127.00, z=17.85]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 141495360 bytes (134 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms1G
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2065 Optifine OptiFine_1.10.2_HD_U_C2 23 mods loaded, 23 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2065.jar) 
    UCHIJA  Forge{12.18.1.2065} [Minecraft Forge](forge-1.10.2-12.18.1.2065.jar) 
    UCHIJA  BetterFoliage{2.1.0} [Better Foliage](BetterFoliage-MC1.10-2.1.0.jar) 
    UCHIJA  BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
    UCHIJA  Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJA  chancecubes{1.10-2.2.1.120} [Chance Cubes](ChanceCubes-1.10-2.2.1.120.jar) 
    UCHIJA  EnderZoo{1.10-1.2.3.43} [Ender Zoo](EnderZoo-1.10-1.2.3.43.jar) 
    UCHIJA  gravestone{1.5.5} [Gravestone](GraveStone Mod 1.5.5.jar) 
    UCHIJA  InfernalMobs{1.7.1} [Infernal Mobs](InfernalMobs-1.10.jar) 
    UCHIJA  JEI{3.9.0.244} [Just Enough Items](jei_1.10.2-3.9.0.244.jar) 
    UCHIJA  jeresources{0.4.8.48} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.8.48.jar) 
    UCHIJA  lucky{7.3.0} [Lucky Block](LuckyBlock_1-10-2_v7-3-0.zip) 
    UCHIJA  mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-1.10.2-0.10.4.jar) 
    UCHIJA  RadixCore{1.10.2-2.1.3} [RadixCore](RadixCore-1.10.2-2.1.3-universal.jar) 
    UCHIJA  MCA{1.10.2-5.2.2} [Minecraft Comes Alive](MCA-1.10.2-5.2.2-universal.jar) 
    UCHIJA  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2b.jar) 
    UCHIJA  randomthings{3.7.5} [Random Things](RandomThings-MC1.10.2-3.7.5.jar) 
    UCHIJA  AS_Ruins{16.2} [Ruins Spawning System](Ruins-1.10.jar) 
    UCHIJA  SophisticatedWolves{3.6.1} [SophisticatedWolves](SophisticatedWolves-3.6.3.jar) 
    UCHIJA  StorageDrawers{1.10.2-3.2.5} [Storage Drawers](StorageDrawers-1.10.2-3.2.5.jar) 
    UCHIJA  tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UCHIJA  torohealthmod{1.10.2-1} [ToroHealth Damage Indicators](torohealth-1.10.2-1.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13417 Compatibility Profile Context 15.301.1901.0' Renderer: 'AMD Radeon HD 7600G'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)

```
Launched Version: 1.10.2-forge1.10.2-12.18.1.2065
LWJGL: 2.9.4
OpenGL: AMD Radeon HD 7600G GL version 4.5.13417 Compatibility Profile Context 15.301.1901.0, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD A8-4555M APU with Radeon(tm) HD Graphics 
```
