### ISSUE TITLE
Exception loading model errors

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#787]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.

## Versions

Minecraft: 1.10.2
Forge: 12.18.1.2076-universal
MCA: 5.2.3
RadixCore: 2.1.3

## Issue Description

The game with the mod installed seems to work so far, but I get a lot of errors bloating the log indicating missing files or similar problems.

## Reproduce Steps
1. Start Minecrat with mod installed.
2. Take a look in the log / game output in the launcher.

## Additional Information

```
[08:52:25] [Client thread/ERROR] [FML]: Exception loading model for variant mca:BlockVillagerBedGreen#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model mca:item/BlockVillagerBedGreen with loader VanillaLoader.INSTANCE, skipping
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:317) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170) ~[byo.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.FileNotFoundException: mca:models/item/BlockVillagerBedGreen.json
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:311) ~[byo.class:?]
    at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:118) ~[ModelLoader.class:?]
    at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:868) ~[ModelLoader$VanillaLoader.class:?]
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
    ... 17 more
```

**Comment by WildBamaBoy** [comment]
This is a non-issue, items should appear just fine even with the error messages.

**Comment by ghost** [comment]
Well... where I come from, bloating a log with error messages while the program just works fine is an issue, as it needlessly extends the debugging process. It's a matter of good practice.

**Comment by WildBamaBoy** [comment]
Blame horrible documentation of the JSON model format, not me.

**Comment by ghost** [comment]
Who is responsible for the JSON model format?

**Comment by WildBamaBoy** [comment]
Mojang.

**Comment by ghost** [comment]
So you're saying Minecraft itself throughs this error for a missing model while it actually is not missing?

I posted the issue also [here](https://github.com/RootsTeam/Roots/issues/116) and [here](https://github.com/The-Fireplace/Adobe-Blocks/issues/2), and they were able to fix it. Maybe they can tell you what the horrible documentation of the JSON model format can't?

Don't want to blame anyone.

**Comment by WildBamaBoy** [comment]
I'm not really interested spending time fixing a non-issue. I'd rather spend time _(what little I have)_ fixing actual problems. Try to ignore it.

**Comment by WildBamaBoy** [comment]
Not meaning to sound snappy, by the way. I will take a look at those issues but there are other things I need to prioritize first.
