### ISSUE TITLE
Crash on loading or creating world

### ISSUE THREAD

**Issue by AlienXtream** [WildBamaBoy/minecraft-comes-alive#813]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [untested] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

MCA 5.2.3
RadixCore 2.1.3

upon loading a world the game crashes

crash header;
Time: 12/2/16 4:29 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mca.core.MCA.getPlayerData(MCA.java:700)
	at mca.packets.PacketPlayerDataC.processOnGameThread(PacketPlayerDataC.java:55)
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:161)
	at mca.core.forge.EventHooksFML.clientTickEventHandler(EventHooksFML.java:135)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_755_EventHooksFML_clientTickEventHandler_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

full report;
[crash-2016-11-15_20.11.36-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/625356/crash-2016-11-15_20.11.36-client.txt)

**Comment by AlienXtream** [comment]
appears to occur only when no saves are present

**Comment by TimWaterham** [comment]
Yup a friend of mine had this when joining my Dedicated Server, any update about this ?

**Comment by WildBamaBoy** [comment]
Reproduce the issue with just MCA and RadixCore installed.

**Comment by EPIICTHUNDERCAT** [comment]
just got this right now. interesting
