### ISSUE TITLE
Crash on socializing

### ISSUE THREAD

**Issue by AlienXtream** [WildBamaBoy/minecraft-comes-alive#814]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

1.10.2 

when i attempt to socialize with villagers the game crashes

^

Time: 12/4/16 1:02 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.world.World.func_175688_a(World.java:1079)
	at mca.ai.AIMood.onUpdateClient(AIMood.java:74)
	at mca.ai.AIManager.onUpdate(AIManager.java:40)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:375)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_175688_a(World.java:1079)
	at mca.ai.AIMood.onUpdateClient(AIMood.java:74)
	at mca.ai.AIManager.onUpdate(AIManager.java:40)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:375)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityHuman (mca.entity.EntityHuman)
	Entity ID: 193
	Entity Name: Allanah
	Entity's Exact location: -229.50, 64.00, -215.30
	Entity's Block location: World: (-230,64,-216), Chunk: (at 10,4,8 in -15,-14; contains blocks -240,0,-224 to -225,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)

**Comment by WildBamaBoy** [comment]
Fixed in upcoming update.
