### ISSUE TITLE
[1.10.2] Game crash when EnderIO Killer Joe is active.

### ISSUE THREAD

**Issue by desvandev** [WildBamaBoy/minecraft-comes-alive#817]
## Versions
Minecraft 1.10.2
MCA 5.2.3-universal

## Issue Description
I built Killer Joe from EnderIO then once I turn it on game crashed. MCA npc's were 2 chunks away from Killer Joe. I disable MCA and everything worked fine.

## Reproduce Steps
Place EnderIO's Killer Joe having some MCA NPC's in a loaded chunk. Turn it on.

## Additional Information
Time: 12/5/16 2:03 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mca.data.PlayerMemory.<init>(PlayerMemory.java:50)
	at mca.entity.EntityHuman.getPlayerMemory(EntityHuman.java:1052)
	at mca.core.forge.EventHooksForge.onLivingAttack(EventHooksForge.java:281)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_581_EventHooksForge_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:498)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:820)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73)
	at net.minecraft.entity.monster.EntityEnderman.func_70097_a(EntityEnderman.java:352)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1226)
	at crazypants.enderio.machine.killera.TileKillerJoe.processTasks(TileKillerJoe.java:247)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:216)
	at crazypants.enderio.machine.killera.TileKillerJoe.doUpdate(TileKillerJoe.java:166)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mca.data.PlayerMemory.<init>(PlayerMemory.java:50)
	at mca.entity.EntityHuman.getPlayerMemory(EntityHuman.java:1052)
	at mca.core.forge.EventHooksForge.onLivingAttack(EventHooksForge.java:281)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_581_EventHooksForge_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:498)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:820)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73)
	at net.minecraft.entity.monster.EntityEnderman.func_70097_a(EntityEnderman.java:352)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1226)
	at crazypants.enderio.machine.killera.TileKillerJoe.processTasks(TileKillerJoe.java:247)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:216)
	at crazypants.enderio.machine.killera.TileKillerJoe.doUpdate(TileKillerJoe.java:166)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)

-- Block entity being ticked --
Details:
	Name: blockKillerJoeTileEntity // crazypants.enderio.machine.killera.TileKillerJoe
	Block type: ID #961 (tile.blockKillerJoe // crazypants.enderio.machine.killera.BlockKillerJoe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (17,50,-336), Chunk: (at 1,3,0 in 1,-21; contains blocks 16,0,-336 to 31,255,-321), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #961 (tile.blockKillerJoe // crazypants.enderio.machine.killera.BlockKillerJoe)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: Libertalia 2
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 650 Drop: 0
	Level seed: -1040154011
	Level generator: ID 07 - RTG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3056782 game time, 275648 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 21940 (now: false), thunder time: 13958 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Megistus** [comment]
Can confirm the same crash with EnderIO 1.10.2-3.0.1.141_beta. 
Does not occur with EnderIO 1.10.2-3.0.1.137_beta.

Attempted to report issue with EnderIO folks, but was immediately closed as an MCA issue. Not really, but, what can I do? Ultimately, communication between you two Mod developers would be fantastic to get this issue resolved. 

Thanks much!

**Comment by 4karion** [comment]
Same issue with EnderIO-1.10.2-3.1.171 and MCA-1.10.2-5.2.3-universal
Any updates on this?

**Comment by WildBamaBoy** [comment]
Mod developers, communicate? It'll never happen.

Should be fixed in upcoming update.
