### ISSUE TITLE
EntityChoreFishHook

### ISSUE THREAD

**Issue by bloodyraoul** [WildBamaBoy/minecraft-comes-alive#823]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions
Minecraft 1.10.2
MCA-1.10.2-5.2.3
RadixCore-1.10.2-2.1.3

## Issue Description
The game crash when loading my game

## Reproduce Steps
load the game....crash

## Additional Information
java.lang.NullPointerException: Ticking entity
	at net.minecraft.enchantment.Enchantment.func_185260_a(Enchantment.java:55)
	at net.minecraft.enchantment.EnchantmentHelper.func_185284_a(EnchantmentHelper.java:200)
	at net.minecraft.enchantment.EnchantmentHelper.func_151387_h(EnchantmentHelper.java:256)
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java:470)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by WildBamaBoy** [comment]
Fixed in upcoming update.
