### ISSUE TITLE
Unable to open Config GUI

### ISSUE THREAD

**Issue by SerranoPancake** [WildBamaBoy/minecraft-comes-alive#832]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Issue Description
I am unable to open the config options for MCA

## Reproduce Steps
Clicking the config button under mod options

## Additional Information
[14:05:21] [Client thread/ERROR] [FML/]: There was a critical issue trying to build the config GUI for MCA
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
	at net.minecraftforge.fml.client.GuiModList.func_146284_a(GuiModList.java:283) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460) [bft.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_73864_a(GuiModList.java:197) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548) [bft.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_146274_d(GuiModList.java:327) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) [bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at mca.core.Config.getCategories(Config.java:219) ~[Config.class:?]
	at mca.client.gui.GuiConfigPage.<init>(GuiConfigPage.java:17) ~[GuiConfigPage.class:?]
	... 20 more
[14:07:06] [Netty Local Client IO #1/INFO]

**Comment by GameRKade** [comment]
If you're trying to access the Mod Options from the pause screen of your world, that doesn't seem to work.

Try going to the Mods option from the title screen instead. That's what works for me.

**Comment by WildBamaBoy** [comment]
No version provided.
