### ISSUE TITLE
Random crash when creating a new world.

### ISSUE THREAD

**Issue by MechanosG** [WildBamaBoy/minecraft-comes-alive#842]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [ ] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

## Versions
MC 1.10.2
Forge 12.18.3.2254
MCA 5.2.3
RadixCore 2.1.3

## Issue Description
When creating a new world in singleplayer (might happen to servers too but I haven't made enough server worlds to test this), right as the terrain starts to generate and before your player spawns (still at the dirt screen) there's something like a 25-50% chance this crash will happen instead.  Restarting MC and loading the same world will often work without crashing though.  Creating new worlds with the same seed seem to not make much of a difference, sometimes crashing, sometimes not.

## Reproduce Steps
Load MC, drink a soda, eat some pizza, when MC finally loads create a new world, pet your cat, smoke some crack, whatever passes the time, wait and see if a world creates or game crashes.

## Additional Information
I haven't tested to see if this happens with only MCA installed and have only tested it in a modpack.
This is the error I'm getting during the crash.
```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mca.core.MCA.getPlayerData(MCA.java:700)
	at mca.packets.PacketPlayerDataC.processOnGameThread(PacketPlayerDataC.java:55)
	at radixcore.network.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:161)
	at mca.core.forge.EventHooksFML.clientTickEventHandler(EventHooksFML.java:135)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_605_EventHooksFML_clientTickEventHandler_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by archonsd** [comment]
I have the same error:   https://pastebin.com/wP0H0A4H (Crash Log)

[ * ]  I am running the latest mod versions of MCA and RadixCore.
[]    I can reproduce this issue with just MCA and RadixCore installed.
[ * ]  I can provide my Minecraft version and MCA version. [ 1.10.2 MC, MCA-1.10.2-5.2.3-universal ]
[ * ]  I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
        ... bit of a lie checking that, so I added my report to the existing one I just dug up here.
[ * ]  I am crashing and can provide my crash report.

**Comment by TheBrain0110** [comment]
I get the same crash on creating a new world as well. Restarting the game and opening the world again works fine.

**Comment by WildBamaBoy** [comment]
Player data is handled differently in 1.12 - try that version and see if the problem continues.
