### ISSUE TITLE
MCA Crash on 1.12 Server

### ISSUE THREAD

**Issue by digi-tal-it** [WildBamaBoy/minecraft-comes-alive#867]
When starting my 1.12 server, I get the following error:

https://pastebin.com/TcGPSN6y

mc 1.12 (not 1.12.1)
mca 1.12-5.3.0

**Comment by Demodian** [comment]
I had a similar issue.  The mod failed before it could even get to the world creation phase.  My crash log is this:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 8/30/17 8:21 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Comes Alive (mca)
Caused by: java.lang.NoClassDefFoundError: mca/core/Localizer
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:401)
        at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:584)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: mca.core.Localizer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 36 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@1af05b03 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        ... 38 more
Caused by: java.lang.RuntimeException: Attempted to load class mca/core/Localizer for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
        ... 40 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.12
        Operating System: Linux (amd64) version 4.4.0-79-generic
        Java Version: 1.8.0_131, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 677933952 bytes (646 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
        JVM Flags: 2 total; -Xmx1024M -Xms1024M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.40 Powered by Forge 14.21.1.2443 7 mods loaded, 7 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UC      minecraft{1.12} [Minecraft] (minecraft.jar)
        UC      mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
        UC      FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443-universal.jar)
        UC      forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443-universal.jar)
        UC      radixcore{1.12-2.3.0} [RadixCore] (RadixCore-1.12-2.2.0-universal.jar)
        UE      mca{1.12-5.3.0} [Minecraft Comes Alive] (MCA-1.12-5.3.0-universal.jar)
        UC      mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar)
        Loaded coremods (and transformers):
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

**Comment by techfixpros** [comment]
Same issue, here is more information on my platform:

Mint 17.2 rafaela
x86_64 Linux 3.16.0-38-generic
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
forge-1.12-14.21.1.2415-universal.jar
RadixCore-1.12-2.2.0-universal.jar
MCA-1.12-5.3.0-universal.jar

My crash logs match the previous two posters, and it only happens when MCA jar is in the mods folder. Radix core allows forge server to run properly.

**Comment by Zareion** [comment]
Same issue on my end as well.

**Comment by PingPongLee** [comment]
Got this issue too

**Comment by Darkmega18** [comment]
Same crash also on ours. D: just saying. but a massively lot more mods. :V

**Comment by CristianPrundeanu** [comment]
Same crash here. Fresh server install, no other mods.

Not sure if it's related, but this is preceded by a file not found exception for minecraft.jar: _[FML]: Missing English translation for minecraft: minecraft.jar (The system cannot find the file specified)_

Creating a link (_mklink minecraft.jar minecraft_server.1.12.jar_) changes the error to: _[FML]: Missing English translation for mcp: assets/mcp/lang/en_us.lang; java.io.FileNotFoundException: assets/mcp/lang/en_us.lang_

**Comment by josephtingiris** [comment]
same problem

**Comment by dragon3025** [comment]
I also have this problem.

**Comment by Mophise** [comment]
Just adding my crash report in case it helps: https://pastebin.com/pTd0Fxmh
