### ISSUE TITLE
[1.12.2] Render Bug?

### ISSUE THREAD

**Issue by BuilderDan** [WildBamaBoy/minecraft-comes-alive#907]
Hello,

None of my MCA villagers are showing up...
![image](https://user-images.githubusercontent.com/19805371/32338272-832cb842-bfb1-11e7-9735-a86c0ceb0b19.png)

I can provide more information if needed, like a mod list.

**Comment by BuilderDan** [comment]
So I tested MCA with just MCA and Radix core and the bug still persists, I am using the latest forge version, which is likely the culprit. A fix for this would be wonderful.

**Comment by BuilderDan** [comment]
It also appears that everytime you hit a villager the screen turns red... and then when you log out with the screen red this happens to the loading screen:

![image](https://user-images.githubusercontent.com/19805371/32339408-f112ef04-bfb4-11e7-8365-97a7f97dcfe1.png)

Red screen after punch:

![image](https://user-images.githubusercontent.com/19805371/32339457-0ab5c09e-bfb5-11e7-86e9-edbbfd042612.png)

**Comment by Galindorf** [comment]
I had this same thing happen, I murdered my husband's invisible children (MWAHAHHAHAA). I wanted to add that my screen turned back to normal (from being red) after a short time.

**Comment by BuilderDan** [comment]
Got this crash from walking around on my server, your mod has some serious problems...

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SoundFixPatchingLoader (AmbientSounds v2.1.0 mc1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.7.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  LittlePatchingLoader (LittleTiles v1.5.0-pre39 mc1.12.2.jar)
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.68-universal.jar)
  ComfortsLoadingPlugin (comforts-1.12.2-0.0.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2 (1).jar)
  LoadingPlugin (Quark-r1.3-114.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.b128.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1 (1).jar)
  LibrarianLib Plugin (librarianlib-1.12-4.1.jar)
  CreativePatchingLoader (CreativeCore v1.9.4 mc1.12.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12-1.9 (1).jar)
  Extra Alchemy ASM (extraalchemy-0.3.5-release.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 11/7/17 1:40 AM
Description: Unexpected error

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215)
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678)
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800)
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1608)
	at DynamicLights.getLightLevel(DynamicLights.java:336)
	at DynamicLights.updateMapDynamicLights(DynamicLights.java:121)
	at DynamicLights.update(DynamicLights.java:95)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1170)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1716)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215)
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678)
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800)
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1608)
	at DynamicLights.getLightLevel(DynamicLights.java:336)
	at DynamicLights.updateMapDynamicLights(DynamicLights.java:121)
	at DynamicLights.update(DynamicLights.java:95)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1170)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1716)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)

**Comment by bconn96** [comment]
+1 for this issue. I can't even see shadows or nametags, though. I only know the NPCs are there because they talk to me and occasionally open doors. This happens when MCA and RadixCore are the only mods.

**Comment by WildBamaBoy** [comment]
#917
